### ISSUE TITLE
Create check for availability of the root trust-anchor

### ISSUE THREAD

**Issue by wtoorop** [getdnsapi/getdns#101]
This is very usable for package maintainers to check if getdns can find the root trust-anchor they configured.  A tip from Paul Wouters.

**Comment by shollenbeck** [comment]
Willem, how would this be different than the current getdns_root_trust_anchor() function?

**Comment by wtoorop** [comment]
Scott, (sorry I just saw your comment), this is exactly the same.  I believe Paul just wanted getdns_root_trust_anchor() to be exposed by a command-line utility.  The getdns_query tool now does this with the -k flag.
