### ISSUE TITLE
stub mode and return_dnssec_status returns error 901

### ISSUE THREAD

**Issue by ngoyal** [getdnsapi/getdns#102]
I'm not sure what the proper behavior is here, but I'm skeptical of this.  Here is a sample that hopefully demonstrates it.  I have a root key in the proper location.  This is against 0.2.0.  I passed --with-ssl and --with-trust-anchor to configure, but that's it.

```c
//
//  main.c
//  Test
//
//  Created by Goyal, Neel on 6/2/15.
//  Copyright (c) 2015 getdnsapi. All rights reserved.
//

#include <stdio.h>
#include <getdns/getdns.h>
#include <getdns/getdns_extra.h>

void issue_req(getdns_context *context) {
    /* Set up the getdns_sync_request call */
    const char * this_name  = "getdnsapi.net";
    uint8_t this_request_type = GETDNS_RRTYPE_A;
    getdns_dict * this_response = NULL;
    
    /* Make the call */
    getdns_return_t dns_request_return = getdns_general_sync(context, this_name, this_request_type,
                                                             NULL, &this_response);
    if (dns_request_return != GETDNS_RETURN_GOOD) {
        printf("Failed to issue request %d\n", dns_request_return);
        return;
    }
    uint32_t this_error;
    getdns_dict_get_int(this_response, "status", &this_error);  // Ignore any error
    if (this_error != GETDNS_RESPSTATUS_GOOD)  // If the search didn't return "good"
    {
        printf("The search had no results, and a return value of %d. Exiting.\n", this_error);
        getdns_dict_destroy(this_response);
        return;
    }
    char* result = getdns_pretty_print_dict(this_response);
    printf("%s\n", result);
    free(result);
    getdns_dict_destroy(this_response);
    return;
}

int main(int argc, const char * argv[]) {
    /* Create the DNS context for this call */
    getdns_context *this_context = NULL;
    getdns_return_t context_create_return = getdns_context_create(&this_context, 1);
    if (context_create_return != GETDNS_RETURN_GOOD)
    {
        fprintf(stderr, "Trying to create the context failed: %d\n", context_create_return);
        return(GETDNS_RETURN_GENERIC_ERROR);
    }
    getdns_context_set_resolution_type(this_context, GETDNS_RESOLUTION_STUB);
    printf("****** FIRST REQUEST *****\n");
    issue_req(this_context);
    
    printf("**** SECOND REQUEST *****\n");
    getdns_context_set_return_dnssec_status(this_context, GETDNS_EXTENSION_TRUE);
    issue_req(this_context);

    getdns_context_destroy(this_context);
        
    return 0;
}
```

The first request is fine.  The second request fails with:

```
The search had no results, and a return value of 901. Exiting.
```

Is this expected behavior?  I ask because this appears to have worked in the past due to some getdns-node binding automated tests.  If things have changed and this is invalid, no worries - I will just update the tests and such.

**Comment by wtoorop** [comment]
Hi Neel,

I am getting GETDNS_RESPSTATUS_GOOD twice.  Your failure might be caused
by lack of DNSSEC capabilities of your upstream resolver.  I've just
started a research to detect and anticipate upstream resolver
capabilities last Monday.  Entry 11 here:
 http://delaat.net/rp/2014-2015/index.html .

You could always test stub DNSSEC resolving by targeting a know to be
good DNSSEC resolver, like 8.8.8.8 for example.

B.t.w.  There is a command line utility in the src/test directory that
can be used to try out simple queries in different modes and with
different extensions.  You can build it with "make getdns_query" in the
root of the tarbal or repo, or in the test directory.

usage: getdns_query [@<server>] [+extension] [<name>] [<type>]
options:
	-a	Perform asynchronous resolution (default = synchronous)
	-A	address lookup (<type> is ignored)
	-b <bufsize>	Set edns0 max_udp_payload size
	-D	Set edns0 do bit
	-d	clear edns0 do bit
	-F <filename>	read the queries from the specified file
	-G	general lookup
	-H	hostname lookup. (<name> must be an IP address; <type>
		is ignored)
	-h	Print this help
	-i	Print api information
	-I	Interactive mode (> 1 queries on same context)
	-j	Output json response dict
	-J	Pretty print json response dict
	-p	Pretty print response dict
	-r	Set recursing resolution type
	-s	Set stub resolution type (default = recursing)
	-S	service lookup (<type> is ignored)
	-t <timeout>	Set timeout in miliseconds
	-T	Set transport to TCP only
	-O	Set transport to TCP only keep connections open
	-L	Set transport to TLS only keep connections open
	-E	Set transport to TLS with TCP fallback only keep
		connections open
	-u	Set transport to UDP with TCP fallback
	-U	Set transport to UDP only
	-B	Batch mode. Schedule all messages before processing
		responses.
	-q	Quiet mode - don't print response


Cheers,
-- Willem

Op 03-06-15 om 03:57 schreef ngoyal:

**Comment by ngoyal** [comment]
awesome tool - had no idea.  Been out of the loop!  You're right re: upstream resolver - worked after setting to 8.8.8.8.  Is 901 the right response code in the case where the upstream is incapable?

**Comment by wtoorop** [comment]
Op 03-06-15 om 15:38 schreef ngoyal:
> awesome tool - had no idea. Been out of the loop! You're right re:
> upstream resolver - worked after setting to 8.8.8.8. Is 901 the right
> response code in the case where the upstream is incapable?

Well... the actual response could differ depending on how (amount and
way) incapable the upstream is.  The research project that I mentioned
will be looking into this and hopefully a will result in a taxonomy so
we can name the different ways and amount those upstreams are broken :).

**Comment by ngoyal** [comment]
Excellent - thanks, Willem!
