### ISSUE TITLE
0.3.0 release candidate fprintf in context.c

### ISSUE THREAD

**Issue by shollenbeck** [getdnsapi/getdns#107]
I found this while testing the PHP language bindings. There's a call to fprintf in context.c that's causing record information to be printed to stderr. The fix is to remove the call;here's a patch:

diff --git src/context.c src/context.c
index f7b87f8..817cc3f 100644
--- src/context.c
+++ src/context.c
@@ -2067,7 +2067,6 @@ priv_getdns_ns_dns_setup(struct getdns_context *context)

                                (void) gldns_wire2str_rr_buf(rr->pos,
                                    rr->nxt - rr->pos, ta_str, sizeof(ta_str));
-                               fprintf(stderr, "TA: %s\n", ta_str);
                                (void) ub_ctx_add_ta(
                                    context->unbound_ctx, ta_str);
                        }

**Comment by wtoorop** [comment]
Thanks Scott.  fprintf was removed in the actual release.
