### ISSUE TITLE
UDP only transport returns generice error on truncated packet

### ISSUE THREAD

**Issue by wtoorop** [getdnsapi/getdns#114]
See: getdns_query -s -U large.getdnsapi.org A

It should just return the truncated packet of course.

Full recursive might not be able to complete when UDP only (or TCP only for that matter).
Currently we have timeout on the query above.  Investigate.

**Comment by saradickinson** [comment]
Hi Willem, 

I think the problem here is that '-U' means UDP_ONLY. Try using '-u' instead, which means allow fallback to TCP (or use the list format '-l UT' compared to '-l U')

**Comment by wtoorop** [comment]
Yes I know that.  Point is, that if fallback is not allowed, it should return the truncated packet and not generic error

**Comment by wtoorop** [comment]
Commit 0a809cb7d80341f05e15f599c916dc6598a8c2e4 resolves this issue.
