### ISSUE TITLE
STUB mode not honored if query has already been performed in RECURSING mode

### ISSUE THREAD

**Issue by glenwiley** [getdnsapi/getdns#13]
After Glen and I agreed that query tests should be done in both recursive and stub mode I began changing my getdns_general() test suite to issue a query in recursive mode, then switch to stub mode, and issue another query. For the recursive query, I query something like "google.com" A and generically verify that I get address records in the ANSWER section, etc. For the stub mode query, I am querying a local named server I setup with a canned zone file. In this case, I actually verify that I get the exact response recorded in a character constant defined in a header file that was produced by my "golden master" test program. What I've found is that if I do the "google.com" query in recursive mode that the next query for "kitchensink.net" is also done in recursive mode even though I've switched the context to stub mode. I know this because the real "kitchensink.net" returns different records (A, SOA, etc.) than my test zone file does. If I comment out the getdns_general() call to query "google.com" then the stub mode test passes (i.e., I get the expected response).

For now to keep my test progress flowing, I am going to destroy and recreate the context between these two queries.

-----
Neel:

We will need to re-create the unbound context. I think this is a valid bug for sure. The specification doesn't call out details on what happens to outbound requests when the resolution mode changes. I think we should document our approach in our implementation specific documentation. I propose the following for our initial release:

    setting the resolution mode to something different sets a flag (just like it does today).
    the context update callback is fired if one is set
    when a query is issued and the resolution mode has changed, then all outbound requests are canceled prior to the new query being sent. The callback type will be GETDNS_CALLBACK_CANCEL. Alternatively, we can not fire the callback, or propose a new type that is a bit more descriptive than cancel.

(#113 from private repo)

**Comment by wtoorop** [comment]
0.1.6 was only bugfixes.  This has to wait for release 0.1.7.

**Comment by wtoorop** [comment]
Done in the release candidate!
