### ISSUE TITLE
Convert master file format to getdns data structs

### ISSUE THREAD

**Issue by ngoyal** [getdnsapi/getdns#14]
It would be useful to add an API where a trust anchor file can be added on a per context basis after it has been created.  This may follow the [context finalization](https://github.com/getdnsapi/getdns/wiki/Implementation%20Specific%20Details#wiki-context-finalization) rules.  Mobile platforms can certainly benefit from this.

The API can be added to getdns_extra.h and then brought into the official header when we agree on a signature.  I suggest something like:
`getdns_return_t getdns_context_add_trust_anchor(getdns_context* context, const char* path);`  which is a mirror of the unbound API.

Should we take in a user specified format (unbound, bind, etc.) as well?

**Comment by wtoorop** [comment]
Maybe we can generalize this to a function that would parse master file format and convert into getdns_list of RR dicts.  Internally we already have this function.  Should we expose?

**Comment by MelindaShore** [comment]
On 9/29/15 4:10 AM, wtoorop wrote:
> Maybe we can generalize this to a function that would parse master file
> format and convert into getdns_list of RR dicts. Internally we already
> have this function. Should we expose?

Yes!  I've seen at least one person attempt to do this in
Python (which is why I've started work on an RR object).

Melinda

-- 
Melinda Shore
No Mountain Software
melinda.shore@nomountain.net

"Software longa, hardware brevis."

**Comment by wtoorop** [comment]
Done with commit 8ebb0476937ff047fe3f73ab6242c216b47fba0d
Functions have doxygen style documentation in src/getdns/getdns_extra.h.in
Usage examples in src/test/tpkg/260-conversion-functions.tpkg/260-conversion-functions.c
