### ISSUE TITLE
Need method to set opcode for new DNS uses.

### ISSUE THREAD

**Issue by pusateri** [getdnsapi/getdns#165]
Some of the new DNS drafts use different opcodes than the standard query.

**Comment by wtoorop** [comment]
Thank you Tom,

I've done a pull request for this feature.
A usage example can be found in the unit test: https://github.com/wtoorop/getdns/blob/features/send_query_packet/src/test/tpkg/270-header-extension.tpkg/270-header-extension.c

I hope this works for you, if not, let me know.

**Comment by pusateri** [comment]
I've checked it out and will try it. Thanks!
