### ISSUE TITLE
Current Makefile layout prevents simultaneous job execution (-j commandline option to make)

### ISSUE THREAD

**Issue by wtoorop** [getdnsapi/getdns#166]
Because our Makefile runs make for the Makefiles in the subdirectory, when make -j is called, this results in multiple makes for the subdirectory, which will conflict.
To resolve we have merge everything into a single Makefile.

**Comment by wtoorop** [comment]
Although a single, non-recursive Makefile has many advantages, it is not necessary for simultaneous job execution.  Carefully indicating subdirectory dependencies already resolved the issue with our Makefile: See commit db856f5227bde0de8460c98831770656c36b7a1c .

**Comment by saradickinson** [comment]
Issues still seen with homebrew builds if ```ENV.deparallelize``` removed from the formula:
[homebrew_build_fail.txt](https://github.com/getdnsapi/getdns/files/1084512/homebrew_build_fail.txt)
However using separate 'make' and 'make install' commands is a workaround for this problem. 

A fix has been submitted https://github.com/getdnsapi/getdns/commit/a07290a9b0d1bb922552f81a91f96432dda0706b

**Comment by wtoorop** [comment]
One more commit was needed for this: 3e221ebe

**Comment by wtoorop** [comment]
assuming this is resolved (I can do parallel make install, so I guess it is)
