### ISSUE TITLE
typo in API section 3.3 and clarification in section 1.3

### ISSUE THREAD

**Issue by pusateri** [getdnsapi/getdns#173]
It says:  Each list time contains two names

It should say: Each list item is a dictionary that contains two names

**Comment by pusateri** [comment]
Also, section 1.3 says:
The address is given as a getdns_dict data structure (defined below). The list must have two names: address_type (whose value is a bindata; it is currently either "IPv4" or "IPv6" (which are case-sensitive)) and address_data (whose value is a bindata).

It seems confusing to say "The list must have two names". Instead maybe say "Each list item is a dictionary that contains two names."

**Comment by MelindaShore** [comment]
On 5/16/16 9:42 AM, Tom Pusateri wrote:
> It seems confusing to say "The list must have two names". Instead maybe
> say "Each list item is a dictionary that contains two names."

Come to think of it, "names" should probably be "keys."

Melinda

**Comment by pusateri** [comment]
Even better!

**Comment by wtoorop** [comment]
Resolved.
The spec is currently maintained here b.t.w.: https://github.com/getdnsapi/getdns-website/blob/master/content/documentation/spec/contents.lr
