### ISSUE TITLE
spec doesn't explain difference between create variants

### ISSUE THREAD

**Issue by pusateri** [getdnsapi/getdns#174]
The spec lists two ways to create lists with no distinction:
getdns_list \* getdns_list_create();
getdns_list \* getdns_list_create_with_context(
  getdns_context *context
);

I might guess that the first has to be freed by the user and the second is freed when the context is destroyed but this is only a guess.

Same for dicts.

**Comment by wtoorop** [comment]
No, this is not the case.  The create_with_context versions will copy the custom memory functions from the context.  This needs explaining in the spec yes.  Thanks!

**Comment by wtoorop** [comment]
Resolved.
The spec is currently maintained here b.t.w.: https://github.com/getdnsapi/getdns-website/blob/master/content/documentation/spec/contents.lr
