### ISSUE TITLE
Bug report: pip install fails for 3.4.4 on Mac OS 10.10.5

### ISSUE THREAD

**Issue by tjsoftworks** [getdnsapi/getdns#178]
(badguys) Tue May 31 14:00:01 admin >>pip install getdns
Collecting getdns
  Downloading getdns-0.6.1.tar.gz
Installing collected packages: getdns
  Running setup.py install for getdns ... error
    Complete output from command /usr/local/opt/pyenv/versions/3.4.4/envs/badguys/bin/python3.4 -u -c "import setuptools, tokenize;**file**='/private/var/folders/gg/bk91_2dd7f350l2js_kdvyzh0000gn/T/pip-build-8sul0365/getdns/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/gg/bk91_2dd7f350l2js_kdvyzh0000gn/T/pip-73t1kps0-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/opt/pyenv/versions/3.4.4/envs/badguys/include/site/python3.4/getdns:
    running install
    running build
    running build_ext
    building 'getdns' extension
    creating build
    creating build/temp.macosx-10.10-x86_64-3.4
    clang -Wno-unused-result -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/include -I/usr/local/opt/pyenv/versions/3.4.4/envs/badguys/include -I/usr/local/opt/pyenv/versions/3.4.4/include/python3.4m -c getdns.c -o build/temp.macosx-10.10-x86_64-3.4/getdns.o -g
    getdns.c:43:10: fatal error: 'getdns/getdns.h' file not found
    #include <getdns/getdns.h>
             ^
    1 error generated.
    error: command 'clang' failed with exit status 1

```
----------------------------------------
```

Command "/usr/local/opt/pyenv/versions/3.4.4/envs/badguys/bin/python3.4 -u -c "import setuptools, tokenize;**file**='/private/var/folders/gg/bk91_2dd7f350l2js_kdvyzh0000gn/T/pip-build-8sul0365/getdns/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /var/folders/gg/bk91_2dd7f350l2js_kdvyzh0000gn/T/pip-73t1kps0-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/opt/pyenv/versions/3.4.4/envs/badguys/include/site/python3.4/getdns" failed with error code 1 in /private/var/folders/gg/bk91_2dd7f350l2js_kdvyzh0000gn/T/pip-build-8sul0365/getdns/

**Comment by wtoorop** [comment]
Closing because in wrong repo
