### ISSUE TITLE
configure is not clear about missing dependencies

### ISSUE THREAD

**Issue by banburybill** [getdnsapi/getdns#202]
Running configure without installing dependencies is not clear about what is missing. Is my problem missing libidn, unbound-event or libunbound, or all of them?

checking for idna_to_ascii_8z in -lidn... no
checking for unbound-event.h... no
configure: Checking for dependency libunbound
checking for ub_fd in -lunbound... no
configure: error: One more dependencies is missing

**Comment by wtoorop** [comment]
Commit 3fa34dcf deals with this.
