### ISSUE TITLE
getdns 0.9.0: getdns_get_suffix() results has end '\0' in bindata

### ISSUE THREAD

**Issue by banburybill** [getdnsapi/getdns#203]
getdns 0.9.0 (Debian package) returns results as bindata, but the results have a trailing '\0'.

In other words, a result 'foo' is returned as 'foo\0' with length 4. For non-C usage it is therefore necessary to look for and remove the trailing '\0'.

**Comment by wtoorop** [comment]
Acknowledged.  Will be fixed with commit: 4ea4f684
