### ISSUE TITLE
Use strict semantic versioning for pre-release versions

### ISSUE THREAD

**Issue by joelpurra** [getdnsapi/getdns#208]
As specified in [semantic versioning](http://semver.org/) v2.0.0, [pre-release version numbers](http://semver.org/#spec-item-9) must have a hyphen to separate the patch version and the pre-release name: `v1.0.0-b2`.

> [9.](http://semver.org/#spec-item-9) A pre-release version MAY be denoted by appending a hyphen and a series of dot separated identifiers immediately following the patch version. Identifiers MUST comprise only ASCII alphanumerics and hyphen [0-9A-Za-z-]. Identifiers MUST NOT be empty. Numeric identifiers MUST NOT include leading zeroes. Pre-release versions have a lower precedence than the associated normal version. A pre-release version indicates that the version is unstable and might not satisfy the intended compatibility requirements as denoted by its associated normal version. Examples: 1.0.0-alpha, 1.0.0-alpha.1, 1.0.0-0.3.7, 1.0.0-x.7.z.92.

The current getdns pre-release naming is in the style `v1.0.0b2` and `v1.1.0a1`. The current format is already good and useful, but in the spirit of following the semver standard, I propose that future pre-releases of getdns introduce this hyphen.

I have [already suggested](https://github.com/getdnsapi/getdns-node/issues/15) that [getdns-node](https://github.com/getdnsapi/getdns-node) switches to the standard, as the default package manager for [node.js](https://nodejs.org), [`npm`](https://npmjs.com/) heavily [relies on semver](https://docs.npmjs.com/files/package.json#version) for [version matching](https://docs.npmjs.com/misc/semver). The version number formatting impact is higher for node-based applications and will most likely be updated to be on the safe side when it comes to release management.

**Comment by fcelda** [comment]
Please, pick whatever but be consistent. I can't configure [release monitoring](https://release-monitoring.org/project/10324/) reliably and I'm getting Fedora bug report for each pre-release of getdns.

Semantic versioning gives nice guidance. If you could also *alpha* instead of just *a*, *beta* instead of just *b*, that would be nice as well.

I'm looking forward to the next stable release! :-)

**Comment by wtoorop** [comment]
Sure, from now on we'll do -alpha3 etc.  How about release candidates?  Should we spell that out too or just -rc1?  Does release monitoring pick the github tag names?  Should we rename all previous release tags to the new format?

**Comment by fcelda** [comment]
Hey, I think -alpha, -beta, -rc1, ... that all will work. :) Thank you. This will indeed be helpful for packagers.

**Comment by wtoorop** [comment]
So you want me to rename all previous release tags?

**Comment by fcelda** [comment]
No, definitely not. Just the feature please. :)

**Comment by wtoorop** [comment]
Just for future release you mean?  Will do!
