### ISSUE TITLE
Update Homebrew formula to fix `brew install --HEAD getdns`, add `--devel`

### ISSUE THREAD

**Issue by joelpurra** [getdnsapi/getdns#209]
On Mac, it's common to use [Homebrew](http://brew.sh/) to install software. There is a [getdns formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/getdns.rb) which targets the latest stable release v0.9.0.

In order to use/test/development the most recent commit (usually on `master`, can also target for example `develop`) use [`--HEAD`](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md#head): `brew install --HEAD getdns`. Unfortunately it doesn't work at the moment and [needs troubleshooting](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting).

For semi-stable usage/testing/development, it would also be good to support [`--devel`](https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/Formula-Cookbook.md#devel): `brew install --devel getdns`. At this point in time I'm not sure if it should target getdns v1.0.0b2 or v1.1.0a1, but either would be an improvement.

It would be useful to fix both `--HEAD` and `--develop`, especially to help contributors to get started. See for example https://github.com/getdnsapi/getdns-node/issues/8.

**Comment by joelpurra** [comment]
My attempt to [get getdns v1.0.0 to build using brew can be seen in this pull request](https://github.com/Homebrew/homebrew-core/pull/11578). Unfortunately brew's build server (presumably used for bottling formulas) failed the build. I'm not sure why, so continued to experiment.

I'd be happy if someone took a look, as I'm not as familiar with the build system and openssl dependency.

1. Installing **getdns v1.0.0** using `brew install getdns` (assuming the pull request has been applied) works.
    - Tests in [@joelpurra/getdns-node](https://github.com/joelpurra/getdns-node), which I've been working on the past couple of days, are unfortunately failing for any queries using TLS (without a TCP/UDP fallback).
    - The same tests pass when building and installing manually from getdns source, which is what I've been using while developing.
    - Brew installs openssl v1.0.2k so the version should not be a problem, right?
1. Made `libevent` a `:recommended` dependency.
    - This means it will be installed by default by `brew install getdns`, but can be disabled using `--without-libevent`.
    - Is this a reasonable change for casual brew/getdns users, as well as other brew formulas depending on getdns? [`libevent` seems to be used "more"](https://github.com/getdnsapi/getdns#extensions-and-event-loop-dependencies) than `libev` or `libuv`.
    - This change needs to be reflected in [the getdns README, which mentions the brew flags](https://github.com/getdnsapi/getdns#homebrew).
1. Added building from the most recent non-stable release with `brew install --devel getdns`.
    - This currently points to **getdns v1.1.0-rc1**, and needs to be updated when it changes.
    - The build currently fails; see below.
1. Added building directly from the **`develop` branch** using `brew install --HEAD getdns`.
    - The build currently fails; see below.

**Build fails**

Both `--HEAD` and `--devel` builds currently fail. A quick look points to some relative paths for `getdns_query` and `stubby` not resolving `../libgetdns.la` properly, but the root cause might be something else.

What do you guys think? Is it fixable? Can't guarantee that my own machine isn't messed up from local development (of getdns and other software), so I'd like someone else to try it out. I think this should work:

```shell
# Fetch my getdns.rb pull request.
# After you're done testing it, you might have to manually revert the patched file in
# /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula
brew pull https://github.com/Homebrew/homebrew-core/pull/11578

# Get rid of the current version, if installed using brew.
brew uninstall --verbose getdns

# v1.0.0
brew install --verbose getdns

# v1.1.0-rc1
brew install --verbose --devel getdns

# From source in the develop branch.
brew install --verbose --HEAD getdns
```

**Current state of getdns.rb**

```shell
brew info getdns.rb
```


```text
getdns: stable 1.0.0 (bottled), devel 1.1.0-rc1, HEAD
Modern asynchronous DNS API
https://getdnsapi.net
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/getdns.rb
==> Dependencies
Required: openssl ✔, unbound ✔, libidn ✔
Recommended: libevent ✔
Optional: libuv ✔, libev ✔
==> Options
--with-libev
	Build with libev support
--with-libuv
	Build with libuv support
--without-libevent
	Build without libevent support
--devel
	Install development version 1.1.0-rc1
--HEAD
	Install HEAD version
```

**Comment by wtoorop** [comment]
Thank you Joel for this good work!  I'll update the README.

**Comment by joelpurra** [comment]
@wtoorop: not sure the READM should be updated just yet -- but if you do, at least mention that TLS isn't working when using `brew`. Also, using `--devel` or `--HEAD` doesn't work at all.

**Comment by joelpurra** [comment]
@wtoorop: actually, don't update the README at all yet -- the pull request hasn't been accepted by `brew`.

**Comment by joelpurra** [comment]
Note: https://github.com/Homebrew/homebrew-core/pull/11578#issuecomment-289697668
> [@fxcoudert](https://github.com/Homebrew/homebrew-core/pull/11578#issuecomment-289697668): Devel build fails with `libtool: error: 'locks.lo' is not a valid libtool object`, after having compiled `locks.c` several times in parallel.

**Comment by saradickinson** [comment]
Hi Joel, 
Thanks so much for working on this - I was actually planning on looking at this soon as I want to create a brew formula specifically for stubby. I'm no expert on this either though. I can't see the problem at first glance but I could try to look at this quite soon if that helps. Might be next week though (I'm at IETF this week).

**Comment by wtoorop** [comment]
I haven't looked myself yet, but the Note from @fxcoudert suggests that brew uses parallel compiling with the -j flag to make.  This doesn't work from the root of getdns, because that Makefile is simply calling make with the Makefiles in src and src/tools.  To quickly resolve is to run the build (i.e. make -j 2 ) from the src and the src/tools directory.  Long term fix might be to have a single Makefile.  I created an issue for this a while ago: https://github.com/getdnsapi/getdns/issues/166

**Comment by joelpurra** [comment]
@saradickinson: a separate formula for stubby would be nice, yes -- might make it easier to promote it as a tool. Not sure how to treat `getdns_query` in that case though, as it's built in basically the same way.

**Comment by joelpurra** [comment]
@wtoorop: there might be a specific brew flag to enable/disable parallel compilation. They have so many formulas basically all and everything has been "done" already.

Another thought is to, based on comments in the stubby documentation, allow the brew flags `--without-libidn` and `--without-unbound` (`--enable-stub-only`). This is just for advanced users, but as the flags are supported in getdns I guess they might as well be for brew.

**Comment by joelpurra** [comment]
I'm about to push some changes to the formula; the [special `ENV.deparallelize`](https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#bad-makefiles) and `--without-libidn` plus `--without-unbound` (`--enable-stub-only`).

**Comment by joelpurra** [comment]
Pushed the new formula version. You can `brew pull` it [as noted above](https://github.com/getdnsapi/getdns/issues/209#issuecomment-289564172).

I don't know if the following `npm run --silent test` errors are due to my machine being misconfigured or not, but they do pass with a build from source.

With `🍺  /usr/local/Cellar/getdns/1.0.0: 97 files, 1.4MB, built in 50 seconds`, plus two more errors with the same message:

```text
  1) TLS Hostname validation should return successfully:
     Error: expected { msg: 'Error issuing query', code: 1 } to equal null
      at Assertion.assert (node_modules/expect.js/index.js:96:13)
      at Assertion.be.Assertion.equal (node_modules/expect.js/index.js:216:10)
      at Assertion.(anonymous function) [as be] (node_modules/expect.js/index.js:69:24)
      at ctx.general (test/tls.js:71:28)
      at Context.ctx.general (getdns.js:54:27)
      at Context.<anonymous> (test/tls.js:70:13)
```

With both `--HEAD` as well as `🍺  /usr/local/Cellar/getdns/1.1.0-rc1: 99 files, 1.7MB, built in 55 seconds`, plus two more errors with the same message:

```text
  1) TLS Hostname validation should return successfully:
     Error: expected { msg: 'Error issuing query', code: 398 } to equal null
      at Assertion.assert (node_modules/expect.js/index.js:96:13)
      at Assertion.be.Assertion.equal (node_modules/expect.js/index.js:216:10)
      at Assertion.(anonymous function) [as be] (node_modules/expect.js/index.js:69:24)
      at ctx.general (test/tls.js:71:28)
      at Context.ctx.general (getdns.js:54:27)
      at Context.<anonymous> (test/tls.js:70:13)
```

Didn't test the new `--without-` flags so far as the getdns-node test suite depends on them.

```shell
brew info getdns
```

```text
getdns: stable 1.0.0 (bottled), devel 1.1.0-rc1, HEAD
Modern asynchronous DNS API
https://getdnsapi.net
Not installed
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/getdns.rb
==> Dependencies
Required: openssl ✔
Recommended: unbound ✔, libidn ✔, libevent ✔
Optional: libuv ✔, libev ✔
==> Options
--with-libev
	Build with libev support
--with-libuv
	Build with libuv support
--without-libevent
	Build without libevent support
--without-libidn
	Build without libidn support
--without-unbound
	Build without unbound support
--devel
	Install development version 1.1.0-rc1
--HEAD
	Install HEAD version
```

**Comment by wtoorop** [comment]
Interesting... the test failed, but only the --only-dependencies tests.  The --devel tests did succeed now? (not completely clear to me from the Jenkins page)

**Comment by joelpurra** [comment]
@wtoorop: I'm also confused, but the other six builds have (per code push) showed up "at some point". Not sure if the brew team triggers them manually, or not. Let's wait a while.

**Comment by joelpurra** [comment]
Last summer I tried to document/[automate the steps I took to build and test on Mac OS X](https://github.com/getdnsapi/getdns-node/pull/6) 10.10 Yosemite. It's specifically geared towards testing getdns/node/getdns-node version combinations, so hope the build scripts are not completely coupled. If everything else fails, @saradickinson and @pusateri might want to have a peek at the build script source, just in case there's some random nugget in there.

Do have some local changes made to those scripts, but would have to review them before pushing any changes. Let me know if there are further questions/issues, and I'll do it.

**Comment by pusateri** [comment]
As mentioned above, this worked for me:
brew pull https://github.com/Homebrew/homebrew-core/pull/11578
brew install --devel getdns

**Comment by joelpurra** [comment]
@pusateri: great!

Note that the code/command block needs to be [fenced with three backticks](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) to show the URL properly. Otherwise look above for the already fenced code which does not prettify the pull request URL.

**Comment by joelpurra** [comment]
Homebrew has now accepted the getdns v1.0.0 pull request; users should be installing/upgrading to it automatically.

Closing this issue. Thanks!
