### ISSUE TITLE
arc4random() is not thread-safe

### ISSUE THREAD

**Issue by neilcook** [getdnsapi/getdns#212]
I get regular segmentation faults when using getdns from a multi-threaded application, all are in the memcpy() in _rs_random_u32(). See [gdb.txt](https://github.com/getdnsapi/getdns/files/553259/gdb.txt)

This is because this entire file is not thread-safe (static variables all over the place). I see that arc4random supposedly locks the call to _rs_random_u32() in locks:
    _ARC4_LOCK();
    _rs_random_u32(&val);
    _ARC4_UNLOCK();

But sadly, _ARC_LOCK() and _ARC_UNLOCK() are stub functions that don't actually do anything.

I'm happy to submit a pull request that implements locking in _ARC_LOCK/_ARC_UNLOCK using pthread_mutex functions, please let me know.

**Comment by wtoorop** [comment]
Thanks for this report!  Yes, I suppose pthreads mutex locks would be good.  But perhaps have an alternative too for when pthreads are not available (windows).

**Comment by neilcook** [comment]
Ok, well I don't know much about Windows programming, but I'll implement the pthread stuff and leave a comment for a TBD for Windows.

**Comment by neilcook** [comment]
Although the pthreads stuff is now merged, I think this issue should remain open until someone implements the Windows locking equivalent

**Comment by wtoorop** [comment]
We have this in the current code base now and it will be in the 1.1.0 release.

**Comment by neilcook** [comment]
When is the 1.1.0 release due?

**Comment by wtoorop** [comment]
Op 12-04-17 om 20:54 schreef Neil Cook:
> When is the 1.1.0 release due?

Uhm... tomorrow :)

**Comment by neilcook** [comment]
Oh great!
