### ISSUE TITLE
cannot build against openssl 1.1.0 stable

### ISSUE THREAD

**Issue by vollkommenheit** [getdnsapi/getdns#214]
When building with openssl-1_1_0-stable (OpenSSL 1.1.0c-dev), I get errors such as this:

> ...
> ./pubkey-pinning.c:317:3: warning: implicit declaration of function 'CRYPTO_w_lock' is invalid in C99 [-Wimplicit-function-declaration]
>                 CRYPTO_w_lock(CRYPTO_LOCK_X509_STORE);
> ...

probably because `CRYPTO_w_lock(CRYPTO_LOCK_X509_STORE);` has been replaced by `X509_STORE_lock(X509_STORE_CTX_get0_store(ctx));` in OpenSSL 1.1.0, as discussed at https://fossies.org/diffs/openssl/1.0.2h_vs_1.1.0/doc/HOWTO/proxy_certificates.txt-diff.html
http://mailing.openssl.dev.narkive.com/zc0wULPM/openssl-dev-openssl-org-4602-missing-accessors

**Comment by wtoorop** [comment]
Thank you for this pointer!  I addresses openssl 1.1.0 (but hadn't merged those commits on the develop branch yet), but I was uncertain what to do with CRYPTO_w_lock and CRYPTO_w_unlock, so I am very pleased with your report!  OpenSSL 1.1.0 support should be on the develop branch now too.  Thanks!

**Comment by vollkommenheit** [comment]
I can confirm that it builds against OpenSSL 1.1.0 on my OS X box now.
