### ISSUE TITLE
getdns 1.1.0a2 missing jsmn/*

### ISSUE THREAD

**Issue by oerdnj** [getdnsapi/getdns#217]
Hi  getdns-1.1.0a2 tarball is missing `src/jsmn/*`. The distribution tarball should be complete and not require git submodules

**Comment by wtoorop** [comment]
Are you sure?  Where did you get that tarbal from? 
This one does have it included: https://getdnsapi.net/dist/getdns-1.1.0-a2.tar.gz

(and has been there since 19 October 14:32 CET)

**Comment by oerdnj** [comment]
Here: https://github.com/getdnsapi/getdns/releases
Perhaps you need to disable that tab in the github? Or manage it manually?

**Comment by wtoorop** [comment]
It appears that github creates those downloads automatically for all tags.  It is unfortunate that it puts those under a tab labelled "Releases".  And this apparently this cannot be turned of :(.
I'm inclined to leave this issue as it is to be honest.  Github is not our release announcement medium. The tarbals it chooses to generate for our tags are not signed with our PGP keys (the tags are).  They are not the official release tarballs.

I'll make sure to refer to the official release tarballs in the tag text for future releases.
Good enough?

**Comment by oerdnj** [comment]
Ok,  then.
