### ISSUE TITLE
In context.c, function set_os_defaults_windows() always call GetNetworkParams() twice

### ISSUE THREAD

**Issue by huitema** [getdnsapi/getdns#225]
The Windows API GetNetworkParams(info,&buflen) can return an error ERROR_BUFFER_OVERFLOW if the length of the parameter "info" indicated in buflen is too short. In that case, the proper behavior is to allocate a new field with the appropriate length, which the code does. However, if the first call does not return an error, there is no point in calling the same method again.

**Comment by wtoorop** [comment]
Indeed!  Thanks for pointing this out and fixing it at the same time :)
So, resolved per 0d13ae6
