### ISSUE TITLE
Incorrect timeout parameter type declaration for upstream_reschedule_events()

### ISSUE THREAD

**Issue by huitema** [getdnsapi/getdns#236]
the signature of the upstream_reschedule_events() function is:

static void
upstream_reschedule_events(getdns_upstream *upstream, size_t idle_timeout)

The use of "size_t" here is problematic, because the timeout parameter is supposedly 64 bit unsigned. In a 64 bit system, that's not a problem, but in a 32 bit system "size_t" is defined as 32 bits unsigned. When calling the function with a 64 bit parameter, the most significant bits will discarded, resultng in unexpected behavior.

**Comment by wtoorop** [comment]
Welll... you fixed it in 50b064a2 :)
Thanks!
