### ISSUE TITLE
Cannot build getdns_query: "No rule to make target 'jsmn/jsmn.h'"

### ISSUE THREAD

**Issue by bortzmeyer** [getdnsapi/getdns#252]
I use the git repository. As of today, configure && make go fine but "make getdnsquery" (or cd src/test; make) fail:

```
% make getdns_query
cd src && make getdns_query
make[1]: Entering directory '/home/stephane/tmp/getdns/src'
cd test && make getdns_query
make[2]: Entering directory '/home/stephane/tmp/getdns/src/test'
make[2]: *** No rule to make target 'jsmn/jsmn.h', needed by 'getdns_str2dict.lo'.  Stop.
make[2]: Leaving directory '/home/stephane/tmp/getdns/src/test'
make[1]: *** [Makefile:157: getdns_query] Error 2
make[1]: Leaving directory '/home/stephane/tmp/getdns/src'
make: *** [Makefile:105: getdns_query] Error 2
```

**Comment by bortzmeyer** [comment]
ArchLinux x86_64, up-to-date, gcc version 6.2.1 20160830

**Comment by wtoorop** [comment]
I just looked, it s in the readme, so closing the ticket.

**Comment by bortzmeyer** [comment]
Yes, it's in the README, I missed it since it is introduced by "If you want to make use of the configuration files that utilise a JSON-like format" and I was not aware I wanted to use them.

Sorry for the false alarm, everything compiles and runs fine now.
