### ISSUE TITLE
[getdns_query] Cannot make -m work (TLS authentication)

### ISSUE THREAD

**Issue by bortzmeyer** [getdnsapi/getdns#254]
getdns_query -h says "-m	Set TLS authentication mode to REQUIRED"

But I cannot make it work:

```
% getdns_query  @2001:4b98:dc2:43:216:3eff:fea9:41a -s -m -l L  www.eff.org       
An error occurred: 1 'Generic error'

All done.
```

I note in INSTALL that I need /usr/local/etc/openssl/certs I is there (linked to the certs directoty of my openssl) but strace shows that getdns_query does not try to open it.

**Comment by wtoorop** [comment]
You need to specify the name too to authenticate (or a pinset).  The return_call_reporting extension can also help to debug.

    $ getdns_query -s @2001:4b98:dc2:43:216:3eff:fea9:41a~dns-resolver.yeti.eu.org -L -m +return_call_reporting
    SYNC response:
    {
      "answer_type": GETDNS_NAMETYPE_DNS,
      "call_reporting":
      [
        {
          "idle timeout in ms": 0,
          "query_name": <bindata for www.eff.org.>,
          "query_to":
          {
            "address_data": <bindata for 2001:4b98:dc2:43:216:3eff:fea9:41a>,
            "address_type": <bindata of "IPv6">
          },
          "query_type": GETDNS_RRTYPE_NS,
          "resolution_type": GETDNS_RESOLUTION_STUB,
          "run_time/ms": 113,
          "tls_auth_status": <bindata of "OK: Server authenticated">,
          "transport": GETDNS_TRANSPORT_TLS
        }
      ],
      "canonical_name": <bindata for eff.map.fastly.net.>,
      "replies_full":
      [
         <bindata of 0x76508180000100010001000103777777...>
      ],
      "replies_tree":
      [
        {
          "additional":
          [
            {
              "do": 0,
              "extended_rcode": 0,
              "rdata":
              {
                "rdata_raw": <bindata of 0x>
              },
              "type": GETDNS_RRTYPE_OPT,
              "udp_payload_size": 4096,
              "version": 0,
              "z": 0
            }
          ],
          "answer":
          [
            {
              "class": GETDNS_RRCLASS_IN,
              "name": <bindata for www.eff.org.>,
              "rdata":
              {
                "cname": <bindata for eff.map.fastly.net.>,
                "rdata_raw": <bindata for eff.map.fastly.net.>
              },
              "ttl": 289,
              "type": GETDNS_RRTYPE_CNAME
            }
          ],
          "answer_type": GETDNS_NAMETYPE_DNS,
          "authority":
          [
            {
              "class": GETDNS_RRCLASS_IN,
              "name": <bindata for fastly.net.>,
              "rdata":
              {
                "expire": 604800,
                "minimum": 30,
                "mname": <bindata for ns1.fastly.net.>,
                "rdata_raw": <bindata of 0x036e7331c0310a686f73746d61737465...>,
                "refresh": 3600,
                "retry": 600,
                "rname": <bindata for hostmaster.fastly.com.>,
                "serial": 2016110301
              },
              "ttl": 19,
              "type": GETDNS_RRTYPE_SOA
            }
          ],
          "canonical_name": <bindata for eff.map.fastly.net.>,
          "header":
          {
            "aa": 0,
            "ad": 0,
            "ancount": 1,
            "arcount": 1,
            "cd": 0,
            "id": 30288,
            "nscount": 1,
            "opcode": GETDNS_OPCODE_QUERY,
            "qdcount": 1,
            "qr": 1,
            "ra": 1,
            "rcode": GETDNS_RCODE_NOERROR,
            "rd": 1,
            "tc": 0,
            "z": 0
          },
          "question":
              "class": GETDNS_RRCLASS_IN,
              "name": <bindata for fastly.net.>,
              "rdata":
              {
                "expire": 604800,
                "minimum": 30,
                "mname": <bindata for ns1.fastly.net.>,
                "rdata_raw": <bindata of 0x036e7331c0310a686f73746d61737465...>,
                "refresh": 3600,
                "retry": 600,
                "rname": <bindata for hostmaster.fastly.com.>,
                "serial": 2016110301
              },
              "ttl": 19,
              "type": GETDNS_RRTYPE_SOA
            }
          ],
          "canonical_name": <bindata for eff.map.fastly.net.>,
          "header":
          {
            "aa": 0,
            "ad": 0,
            "ancount": 1,
            "arcount": 1,
            "cd": 0,
            "id": 30288,
            "nscount": 1,
            "opcode": GETDNS_OPCODE_QUERY,
            "qdcount": 1,
            "qr": 1,
            "ra": 1,
            "rcode": GETDNS_RCODE_NOERROR,
            "rd": 1,
            "tc": 0,
            "z": 0
          },
          "question":
          {
            "qclass": GETDNS_RRCLASS_IN,
            "qname": <bindata for www.eff.org.>,
            "qtype": GETDNS_RRTYPE_NS
          }
        }
      ],
      "status": GETDNS_RESPSTATUS_GOOD
    }
    Response code was: GOOD. Status was: At least one response was returned
    
    All done.

**Comment by wtoorop** [comment]
Here is a config file you can use with the `-C` option of `getdns_query` or use directly with stubby.  It authenticates the remote end with a pin, so you don't need a certificate authority store.  Note that I have also included the yeti root trust anchor too, but did not enabled DNSSEC validation yet ( which needs another line in the config file: `dnssec_return_status: GETDNS_EXTENSION_TRUE` ), because I had an issue with that with the 1.1.0-alpha3 release branch.  I'll look into that...

    { resolution_type: GETDNS_RESOLUTION_STUB
    , edns_client_subnet_private : 1
    , dns_transport_list: [ GETDNS_TRANSPORT_TLS ]
    , tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
    , tls_query_padding_blocksize: 256
    , upstream_recursive_servers:
      [ { address_data: 2001:4b98:dc2:43:216:3eff:fea9:41a
        , tls_pubkey_pinset:
          [ { digest: "sha256"
            , value: 0x55fb587120ad80a75a1c923f3f69ad7018ceb7dad173c2928cd87e71e8c21305
            } ]
        } ]
    , dnssec_trust_anchors:
      [ { name: .
        , type: GETDNS_RRTYPE_DS
        , rdata:
          { keytag: 19444
          , algorithm: 8
          , digest_type: 2
          , digest: 0x2a00eb1d2ed1410cde612acbde1b3c60b06e51da6b6e57575d92b6baa6ef35a2
          } } ]
    }

**Comment by wtoorop** [comment]
I found the issue.  The keytag needed an underscore and should have been called key_tag.  Your stubby for yeti with DNSSEC validation config should thus be:

```
{ resolution_type: GETDNS_RESOLUTION_STUB
, edns_client_subnet_private : 1
, dns_transport_list: [ GETDNS_TRANSPORT_TLS ]
, tls_authentication: GETDNS_AUTHENTICATION_REQUIRED
, tls_query_padding_blocksize: 256
, upstream_recursive_servers:
  [ { address_data: 2001:4b98:dc2:43:216:3eff:fea9:41a
    , tls_pubkey_pinset:
      [ { digest: "sha256"
        , value: 0x55fb587120ad80a75a1c923f3f69ad7018ceb7dad173c2928cd87e71e8c21305
        } ]
    } ]
, dnssec_trust_anchors:
  [ { name: .
    , type: GETDNS_RRTYPE_DS
    , rdata:
      { key_tag: 19444
      , algorithm: 8
      , digest_type: 2
      , digest: 0x2a00eb1d2ed1410cde612acbde1b3c60b06e51da6b6e57575d92b6baa6ef35a2
      } } ]
, dnssec_return_status: GETDNS_EXTENSION_TRUE
}
```

**Comment by bortzmeyer** [comment]
I note that I forgot to say that it works fine with your configuration file (except that the key of the server changed, it is now 0xf239151afe463f7e04ef4fed0eefa3daf9d9d5b8a46b2ca6d90bc5e26917d758). Thanks.

```
% getdns_query  -s -m -l L -C ~/.stubby.conf www.eff.org     
SYNC response:
{
  "answer_type": GETDNS_NAMETYPE_DNS,
  "canonical_name": <bindata for eff.map.fastly.net.>,
  "replies_full":
  [
     <bindata of 0x873d8180000100010001000103777777...>
  ],
  "replies_tree":
...
```
