### ISSUE TITLE
getdns 1.0.0 with libressl-2.4.5 fails to compile

### ISSUE THREAD

**Issue by phicoh** [getdnsapi/getdns#269]
I tried to compile 1.0.0 with libressl 2.4.5 on MacOS. 

This results in:
Undefined symbols:
  "_SSL_CTX_set_min_proto_version", referenced from:
      __getdns_context_prepare_for_resolution in context.o
ld: symbol(s) not found
collect2: ld returned 1 exit status

I had to hack around in configure because there doesn't seem to be an option to disable TLS.

**Comment by wtoorop** [comment]
Thanks, addressed in commit 0da79ae77a1cb30387c9841da18a607ebeb47224 which will be in version 1.1.0 that will be released tomorrow.
