### ISSUE TITLE
Address Selection API?

### ISSUE THREAD

**Issue by huitema** [getdnsapi/getdns#271]
So I have this code that calls getdns_address() and obtains a response. Parsing the response, I can get a list of addresses. What I want to do next, of course, is set up a connection to the selected server. Which API am I supposed to use to choose among the multiple addresses returned from the DNS? Am I supposed to write an implementation of RFC 6724 in the application?

**Comment by wtoorop** [comment]
Yes, I agree, we've started work on this too.  We have a requirements document here: https://docs.google.com/document/d/1gCUk-7vd5Vo10-VFD5jHjpI9QUi1j-Tm7JtWEK1V4_o/edit?usp=sharing . I've pushed some initial work here: https://github.com/getdnsapi/connectbyname
A first implementation of https://tools.ietf.org/html/draft-ietf-v6ops-rfc6555bis-00 would be a good start I think. Want to join?
