### ISSUE TITLE
Decide how to handle OpenSSL errors that are ignorable

### ISSUE THREAD

**Issue by saradickinson** [getdnsapi/getdns#293]
For example OpenSSL verify function will error it if detects a self-signed certification. However in some circumstances (like if a SPKI pin is valid) then the certificate will be acceptable if it passes all other tests. However there is no way to instruct OpenSSL to continue the verification, ignoring that particular error......

**Comment by wtoorop** [comment]
Op 19-04-17 om 15:24 schreef saradickinson:
> For example OpenSSL verify function will error it if detects a
> self-signed certification. However in some circumstances (like if a SPKI
> pin is valid) then the certificate will be acceptable if it passes all
> other tests. However there is no way to instruct OpenSSL to continue the
> verification, ignoring that particular error......

I believe it might be possible to add the self signed certificate to the
store of trusted CA's in such a case...

**Comment by wtoorop** [comment]
Just had a look again.  There is only one way the deal with pinning properly in all circumstances.  Create a temporary CA, sign the pinned certificate and reverify.  Postponing this (again) to 1.3.1 release.

**Comment by wtoorop** [comment]
Just thought about this again.  Method in my last comment will also not suffice.
We could use the DANE functions from OpenSSL >= 1.1.0 instead.  Add the pin as an artificial TLSA with DANE-TA (2) usage type, SPKI  (1) selector and SHA2-256(1) matching type?
We could then try to use the DANE verification code from https://github.com/vdukhovni/ssl_dane for OpenSSL < 1.1.0?
@saradickinson What do you think?

**Comment by saradickinson** [comment]
Crafty - I think that would work! Shame we can't do it directly though.....

**Comment by ArchangeGabriel** [comment]
So if I understand this correctly, it means I am no longer required to comment out `tls_auth_name: "ns0.ldn-fai.net"` in my Stubby config because now self-signed certificates like this one are properly accepted thanks to DANE?

**Comment by wtoorop** [comment]
No this was purely a security fix.
What you are talking about is in the making, but ns0.ldn-fai.net does not have a DANE record, and also is ldn-fai.net not DNSSEC signed, so it will not work for that particular recursive:

```
$ dig _853._tcp.ns0.ldn-fai.ne. TLSA +dnssec

; <<>> DiG 9.11.0-P2 <<>> _853._tcp.ns0.ldn-fai.ne. TLSA +dnssec
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 33440
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
;; QUESTION SECTION:
;_853._tcp.ns0.ldn-fai.ne.	IN	TLSA

;; AUTHORITY SECTION:
ne.			3579	IN	SOA	ns.intnet.ne. root.ns.intnet.ne. 2018021600 21600 3600 3600000 10800

;; Query time: 0 msec
;; SERVER: 185.49.140.100#53(185.49.140.100)
;; WHEN: Thu Feb 22 13:05:03 CET 2018
;; MSG SIZE  rcvd: 104
```

But some will work then:

```
$ dig _853._tcp.getdnsapi.net. TLSA +dnssec

; <<>> DiG 9.11.0-P2 <<>> _853._tcp.getdnsapi.net. TLSA +dnssec
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63926
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 2, AUTHORITY: 4, ADDITIONAL: 5

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
;; QUESTION SECTION:
;_853._tcp.getdnsapi.net.	IN	TLSA

;; ANSWER SECTION:
_853._tcp.getdnsapi.net. 234	IN	TLSA	3 1 1 7E8C59467221F606695A797ECC488A6B4109DAB7421ABA0C5A6D3681 AC5273D4
_853._tcp.getdnsapi.net. 234	IN	RRSIG	TLSA 7 4 450 20180313110636 20180219232955 13950 getdnsapi.net. cOM3n4hFwYPw3NR2MQnNNQREXLIrdpjR5/EETXAx2svRsE4ym9MqSzoD lt5JMo5YhIgypxasSJxYEvly2g66MtdV46P0y2gFXyDN4nsWVx0imbdp Xx1lPWjTHg8/uBtRpXB8idFeJucof4eRJ6SaBI6iJzwkadz3mrfSI62s REQ=

;; AUTHORITY SECTION:
getdnsapi.net.		234	IN	NS	getdnsapi.net.
getdnsapi.net.		234	IN	NS	puck.nether.net.
getdnsapi.net.		234	IN	NS	dicht.nlnetlabs.nl.
getdnsapi.net.		234	IN	RRSIG	NS 7 2 450 20180313005343 20180220052955 13950 getdnsapi.net. m9rDiqsR86uGOq6EN2zY9Ll/hyd4yw6EDlVgyLph0csiHO/3zmv54ELo EptcS3jU/fmR+ED70sgcolTWSWA4DIz+PiMp3ovOXijqJbux402XUn1L a1QGJ+ESKKZI/s4PA0GRWz+lc22hd6UezPTOWZWckiWmbfr3y+hQcZ4W p5E=

;; ADDITIONAL SECTION:
getdnsapi.net.		234	IN	A	185.49.141.37
getdnsapi.net.		234	IN	AAAA	2a04:b900:0:100::37
getdnsapi.net.		234	IN	RRSIG	A 7 2 450 20180313162335 20180220032955 13950 getdnsapi.net. I6kOMJ6deekqRWy4WeruWLy1D8gHfghqoTIkqq78SXSRSKhZGcx1c6ln fFGdfMNo6MYyb+GUoTDrwl4BiBfStC9reBohpq/CXWD4EP4f/L3HRDMh tYiQpv35Os6Yt3nrJaMxKSUY78sw9jyNHTjyRK3PgVmE3V3X8vgFcO8f KsA=
getdnsapi.net.		234	IN	RRSIG	AAAA 7 2 450 20180312045237 20180218192955 13950 getdnsapi.net. kXkB1PlJSb3EFJGPcLOyosyr57Fo/qzG54GmZFHvSgcZWRZXrlPrKoDi AFORJgF9EO8D9frwJhuWOuaYXBc/T49OTV+Qre3vfBTgjjSBgjY/CC03 GbHTVBPx9EiTqcEgvCf1znIQN/B3QfQzkhSP1bxgSBZTq4KgTfCZW3UN rT4=

;; Query time: 0 msec
;; SERVER: 185.49.140.100#53(185.49.140.100)
;; WHEN: Thu Feb 22 13:08:33 CET 2018
;; MSG SIZE  rcvd: 907
``
