### ISSUE TITLE
suggestion for bindata helper functions

### ISSUE THREAD

**Issue by glenwiley** [getdnsapi/getdns#3]
from Duane W during the hackathon:

I used src/example/example-hostname.c as my guide and was confused by this line for a short while:

struct getdns_bindata this_type = { 5, (void *)"IPv4" };

It took me a while to realize 5 was the length of "IPv4". Maybe there could be a helper function to populate a bindata. For example:

struct getdns_bindata this_type;
getdns_bindata_set(&this_type, "IPv4", sizeof("IPv4"));

or

getdns_bindata_set_from_str(&this_type, "IPv4");

(#57 from private repo)

----

I'd like to include the set/modify bindata functions that Bob Steagall's suggested

getdns_return_t getdns_list_set_bindata_2(struct getdns_list *the_list, size_t index, size_t bindata_size, uint8_t *bindata_content);
getdns_dict_set_bindata_2(struct getdns_dict *the_dict, const char *name, size_t bindata_size, uint8_t *bindata_content);
(#64 from private repo)

**Comment by wtoorop** [comment]
This is not really an issue, but more ongoing addition of convenient extra functions
