### ISSUE TITLE
getdns_context_create: Should OpenSSL init still be prevented by param?

### ISSUE THREAD

**Issue by jroyalty** [getdnsapi/getdns#314]
The docs for `getdns_context_create` say that setting the second bit of the `set_from_os` parameter will prevent OpenSSL library initialization.  However, it looks like https://github.com/getdnsapi/getdns/commit/b857e3d7f1b3b2b7089890fdac6563a51d26bb0c dropped support for that.

Did that just get mistakenly squash or is it no longer a feature?

Thanks!

**Comment by neilcook** [comment]
Since that was my commit, I will explain. It was a workaround for a bug. It got fixed properly with a mutex around OpenSSL initialisation, which is a cleaner fix, and wtoorop agreed. So IMO it's no longer a feature.

**Comment by saradickinson** [comment]
Thanks for this - I'll update the documentation to be correct.

**Comment by saradickinson** [comment]
PR #324 should fix this in the documentation.

**Comment by jroyalty** [comment]
Thanks folks!

**Comment by saradickinson** [comment]
#324 was merged so closing the issue
