### ISSUE TITLE
Please remove the SYNC/ASYNC line from getdns_query output

### ISSUE THREAD

**Issue by keltia** [getdnsapi/getdns#315]
`getdns_query`output is not-quite-plain-json as it prefixes all outputs with the ASYNC/SYNC line (as part of a debugging kind of thing).  Please either make it a configurable option (either CLI or config) and off by default.

**Comment by saradickinson** [comment]
[This commit](https://github.com/getdnsapi/getdns/commit/28c41c3495c509bf584ec0da4e0c7ee20fd8fb68) moves this text to the end of output so it is with the other plain text that is output there. Is that sufficient?

**Comment by keltia** [comment]
I have not run the new code but looking at the diff, it seems to be enough for me, thanks!

**Comment by wtoorop** [comment]
I did a commit to remove printing to stdout all-together. (unless -V is used).
Waiting for travis output too, if I didn't forgot anything I'll close the ticket.
By the way, by default getdns_query outputs pseudo json (with primitive types for domain names, constants etc.).  Our implementation does have functions to parse this pseudo python, but if you want json which can be parsed by javascript etc. you have to give the -j or -J parameter too.

**Comment by wtoorop** [comment]
It passed, so closing

**Comment by keltia** [comment]
My use-case was `|jq .` :) — thanks!
