### ISSUE TITLE
getdnsapi/getdns/README.md links to nonexistant wiki pages

### ISSUE THREAD

**Issue by jamesraftery** [getdnsapi/getdns#318]
The _Extensions and Event loop dependencies_ section of `README.md` links to a wiki page which does not exist:

`https://github.com/getdnsapi/getdns/wiki/Asynchronous-Support#wiki-included-event-loop-integrations`

and the _Language Bindings_ section links to:

`https://github.com/getdnsapi/getdns/wiki/Language-Bindings`

**Comment by insomniacslk** [comment]
Not sure why these were removed, as there is no equivalent content in the source repo. The git history of the wiki dates their removal back to the 28th of April 2017.

I think that those pages should be either reinstated, or replaced by a more up-to-date content (and links fixed).

However until this happens, you can recover the original content from the git repo of the wiki (https://github.com/getdnsapi/getdns.wiki.git).
For the `Language-Bindings` page the content simply pointed to the four official bindings, plus a mention to two new bindings under work, i.e.:
```
Bindings have been developed for:
 - [Python](https://github.com/getdnsapi/getdns-python-bindings)
 - [Java](https://github.com/getdnsapi/getdns-java-bindings)
 - [JavaScript (via node)](https://github.com/getdnsapi/getdns-node)
 - [PHP](https://github.com/getdnsapi/getdns-php-bindings)

In addition, bindings for Go and Perl are in progress.
```

For the `Asynchronous-Support` page, the content was removed the same day, and is too large to copy here (and I don't know how to reference to deleted-pages history here). You can get the original content by checking out

**Comment by saradickinson** [comment]
We moved all the documentation to the main getdns website and doxygen and these links were obviously forgotten. The  bindings are available on the website:
https://getdnsapi.net/bindings/
but the link is rather hidden (it as at the foot of the page - we plan to move it to a drop down).

There is a doxygen page on the event loops:
https://getdnsapi.net/doxygen/group__eventloops.html
and the man pages also include most of the text from the old wiki page I believe:
https://getdnsapi.net/documentation/manpages/#ASYNCHRONOUS USE
and a bit more info on the event loops on this page:
https://getdnsapi.net/blog/categories/basic/
but i agree the README.md documentation should be updated to reference these. Will update.

**Comment by saradickinson** [comment]
PR #326 should fix this.

**Comment by wtoorop** [comment]
PR Merged, so closing issue
