### ISSUE TITLE
call_reporting run_time is always zero for GETDNS_RESOLUTION_RECURSING queries

### ISSUE THREAD

**Issue by jamesraftery** [getdnsapi/getdns#319]
Queries with a `resolution_type` of `GETDNS_RESOLUTION_RECURSING` always return a run_time of zero:

 ```
    {
      "query_name": <bindata for getdnsapi.net.>,
      "query_type": GETDNS_RRTYPE_A,
      "resolution_type": GETDNS_RESOLUTION_RECURSING,
      "run_time/ms": 0
    }
```

Queries with type `GETDNS_RESOLUTION_STUB` return a run_time as expected:

```
    {
      "query_name": <bindata for getdnsapi.net.>,
      "query_to":
      {
        "address_data": <bindata for 172.31.0.2>,
        "address_type": <bindata of "IPv4">
      },
      "query_type": GETDNS_RRTYPE_AAAA,
      "resolution_type": GETDNS_RESOLUTION_STUB,
      "run_time/ms": 119,
      "transport": GETDNS_TRANSPORT_UDP,
      "udp_responses_for_this_upstream": 2,
      "udp_timeouts_for_this_upstream": 0
    }
```

This is on FreeBSD 11 with Unbound 1.6, Ldns 1.7 and getdns 1.1.2.

Incidentally, the API docs say that field is named `run_time` not `run_time/ms`.

**Comment by saradickinson** [comment]
Yes - this is correct and is a limitation of the recursive implementation. I will update the documentation to correct the name and be clearer on this known issue.

**Comment by saradickinson** [comment]
PR #325 updates the documentation

**Comment by wtoorop** [comment]
This PR was merged, so closing ticket.
