### ISSUE TITLE
Stubby -i displaying wrong location of root trust anchor and no `root-anchors.xml` and `root-anchors.p7s` created

### ISSUE THREAD

**Issue by hanvinke** [getdnsapi/getdns#354]
I am using Arch with Stubby-git version. 
stubby -i gives me: 
_...
  ],
  "resolution_type": GETDNS_RESOLUTION_STUB,
  "trust_anchor_file": <bindata of "/usr/etc/unbound/getdns-root.key">,
  "version_number": 16908481,
  "version_string": <bindata of "1.2.1rc1">
}
Result: Config file syntax is valid._

This should normally be pointing to `/etc/unbound/getdns-root.key` as default.
It didn't help editing stubby.yml, I tried to add:

_trust_anchor_file: <bindata of "/etc/unbound/getdns-root.key">_
but stubby was unimpressed.
I also get no creation of the `root-anchors.xml` and `root-anchors.p7s` in my `$HOME/.getdns` directory.
However I do have name resolution, not sure if there is any real checking here.
Can someone check if they have the same issue?

[stubby.TXT](https://github.com/getdnsapi/getdns/files/1447906/stubby.TXT)
[stubby -i.TXT](https://github.com/getdnsapi/getdns/files/1447908/stubby.-i.TXT)

**Comment by ArchangeGabriel** [comment]
The value you need to change in the config file is `dnssec_trust_anchors`, I use:
```
dnssec_trust_anchors: "/etc/trusted-key.key"
```
since that is where `dnssec-anchors` package puts it.

**Comment by wtoorop** [comment]
@hanvinke @ArchangeGabriel is correct.  trust_anchor_file is read only information telling you about the default location of the trust-anchor.  If you want to specify trust anchors on a different location, you have to set the filename in the dnssec_trust_anchors directive (like you do in you stubby.TXT attachment).  In your stubby  -I.TXT file I can see the trust anchors are successfully read, because they are listed with dnssec_trust_anchors.

If you request dnssec validation (by enabling the dnssec_return_status extension, like you do in your config file), but you did not specify trust anchors and they are not in the default location pointed to by trust_anchor_file, or the trust anchor gives a BOGUS root DNSKEY key set,  then the root anchor will be fetched from ICANN and stored in the appdata_dir (/home/han/.getdns in your case).

**Comment by hanvinke** [comment]
Thank you for the quick responses.

The new package getdns  1.2.0-1 installs automatically a symlink (to /etc/trusted-key.key) ==> see files: /etc/unbound/getdns-root.key. it doesn't install to /etc/trusted-key.key - in older versions however it was created.

But the problem remains that stubby -i points NOT to the default location which should be /etc/unbound/getdns-root.key but instead points to /**usr**/etc/unbound/getdns-root.key. 
But since there already is a file created by unbound so I suppose the most logical directory for getdns-root.key would be in /etc/unbound/

So it seems stubby is looking automatically in the wrong directory. Where does that information come from - since it is not defined in /usr/etc/stubby/stubby.yml? maybe a leftover from older versions?

/home/han/.getdns  BTW is completely empty and unfortunately stays like that - so the root anchor is not fetched from ICANN or could not be written. It is not listed in the file listings of either stubby-git or  getdns, or should it be created automatically?

If using stubby as a systemd service is the necessary directory also $HOME/.getdns or should this be $ROOT/.getdns? I have created both folders and full access for stubby to /home/han/.getdns and /root/.getdns but there appear no files.

**Comment by wtoorop** [comment]
The default location of trust_anchor_file is determined during configure time (so when compiling the getds library) and can be changed with the --with-trust-anchor=KEYFILE option to configure.
trust anchors will only be downloaded from data.iana.org if you don't have any working trust-anchors configured.  "Working" is determined by whether they can validate the root DNSKEY rrset or not.

**Comment by hanvinke** [comment]
Thank you very much, instead from AUR I compiled from git with _--with-trust-anchor=/etc/unbound/getdns-root.key_. Now _stubby -i_ correctly gives me: "trust_anchor_file": <bindata of "/etc/unbound/getdns-root.key">  

Solved, I suppose someone can add --with-trust-anchor=/etc/unbound/getdns-root.key to the package configuring in AUR?

Do I understand correctly that when stubby points to a none existing directory (like in my case /usr/etc/stubby/ ) it still will look for the default location, even if configured with another trust-anchor file location through -_-with-trust-anchor=KEYFILE_ option?

For testing purpose with no configured working trust-anchors I temporarily renamed /etc/unbound/getdns-root.key and reloaded daemons and started stubby again.

_Stubby -i_ now shows:
_Nov 07 21:12:50 arch.localhost stubby[15524]: Could not configure context with config dict: Generic error
Nov 07 21:12:50 arch.localhost stubby[15524]: Error parsing config file "/usr/etc/stubby/stubby.yml": Generic error
Nov 07 21:12:50 arch.localhost stubby[15524]: WARNING: No Stubby config file found... using minimal default config (Opportunistic Usage)
Nov 07 21:12:50 arch.localhost stubby[15524]: [20:12:50.659916] STUBBY: Starting DAEMON...._

Is that normal? Still no files created in ./home/han/.getdns directory.
No problems however with name-resolving. So still validating the root DNSKEY rrset ?! 
I am sorry for my ignorance.

**Comment by wtoorop** [comment]
No problem hanvinke.  It is clear to me that I should have a better and clearer page describing how the Zero Configuration DNSSEC works.  Also, I think I should rename the trust_anchor_file from api_information (i.e. stubby -i) into default_trust_anchor_location.  I'll try to come back to your other questions later.

**Comment by ArchangeGabriel** [comment]
The package in AUR is crap. That’s all.
It should specify `--sysconfdir=/etc` in the configure line. That’s where all your issues are originating from.

I’ll modify the package on the next release of getdns to point directly on `/etc/trusted-key.key` thanks to `--with-trust-anchor=` then.

**Comment by hanvinke** [comment]
Thanks everybody, working all fine now. I am looking forward to this extra information about "Zero Configuration DNSSEC".

**Comment by hanvinke** [comment]
When installing stubby-git version from AUR I ran into some minor issue. The git version installs stubby.yml file in the directory "/usr/etc/stubby/".
Default location for stubby.yml is "/etc/stubby/stubby.yml" (like the normal stubby version defaults to). 

So there were two options left to solve the problem. I tried to specify the location on the command line using the -C flag. The wiki says it requires a restart of Stubby.

When doing "sudo stubby -C /usr/etc/stubby/stubby.yml" and "sudo systemctl restart stubby" then "stubby -i" still defaults back to "/etc/stubby/stubby.yml". So do I understand correctly that there is no permanent change possible, only during compilation?

So I ended up making a symlink with "sudo ln -s /usr/etc/stubby/stubby.yml /home/han/.stubby.yml".
Maybe ArchangeGabriel can add a comment?

**Comment by ArchangeGabriel** [comment]
As I said above, yes, `stubby-git` in AUR lacks `--sysconfdir=/etc` in the configure line. Else, you can indeed make a symlink or edit/add a drop-in change of the systemd service to specify the config path.

**Comment by hanvinke** [comment]
Thank you ArchangeGabriel,

I hoped someone could tell me if stubby -C  is showing expected behaviour or not. Is it supposed to be volatile or not. That is not quite clear to me from the wiki.

**Comment by wtoorop** [comment]
@hanvinke I think systemd stubby configuration path is configured elsewhere.  stubby is not a control program that influences stubby persistently.  I'll install a arch linux machine myself, to better response to these issues...

**Comment by hanvinke** [comment]
Nice, thanks.
Right now I am trying to figure out why 
_unbound-anchor -a /etc/unbound/trusted-key.key -c /etc/unbound/icannbundle.pem -u data.iana.org -r /etc/unbound/root.hints -f /etc/unbound/unbound.conf -P 443 -F -v_
works giving:
"_/etc/unbound/trusted-key.key has content
debug cert update forced
last successful probe: Wed Nov 29 19:10:01 2017
the last successful probe is recent
have 3 trusted certificates
resolved server address 72.21.81.189
resolved server address 2606:2800:11f:bb5:f27:227f:1bbf:a0e
connect to 2606:2800:11f:bb5:f27:227f:1bbf:a0e
fetched root-anchors/root-anchors.xml (651 bytes)
connect to 72.21.81.189
fetched root-anchors/root-anchors.p7s (4095 bytes)
signer 0: Subject: /O=ICANN/CN=dnssec@iana.org/emailAddress=dnssec@iana.org
the PKCS7 signature verified
XML was parsed successfully, 2 keys
success: the anchor has been updated using the cert_
"
but when substituting data.iana.org for 72.21.81.189, it fails.
The documentation about unbound-anchor -u says "You can pass an IPv4 address  or IPv6 address (no brackets) if you want.".

Also unbound-anchor is fetching root-anchors.xml and root-anchors.p7s files in memory only, not on disk afaics. Does stubby use something similar like unbound-anchor for root anchor update?

**Comment by wcawijngaards** [comment]
Hi hanvinke,

It fails because the HTTPS request then has no website name in it, but
the IP address.  The remote server won't serve this content by IP
address, but requires the name 'data.iana.org' in the query.

Best regards, Wouter

**Comment by hanvinke** [comment]
Thanks again,

It's a pity that unbound also does not parse /etc/hosts entries. Hope to find a way to circumvent this needed (?) DNS query. Keep up the good work!

**Comment by hanvinke** [comment]
I saw today that unbound has had an update to version 1.6.7-3 in Arch Linux. I think it solves the problem of the trust-anchor renewal by making it a post-installation procedure, instead of a ExecStartPre= ... in the Service section.

See https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/unbound&id=1db1a54b13d46652f51fbc9d933dea26b843760d

**Comment by ArchangeGabriel** [comment]
`/etc/hosts/` works for me, even while using unbound. What does your `/etc/nsswitch.conf` contains? I think the issue lies there.

Also, regarding unbound update, the change you link to is 10 months old. So it has been included for quite some time. And yes, it fixed the issue of updating the `trusted-key.key` by updating it when the dnssec-anchors package get updated, rather than at each start or so. But in both cases you shouldn’t have any issue with that.

**Comment by hanvinke** [comment]
Oh I am sorry,  got the wrong link - fixed it. But you are right- it is merely a simple hook, not a real solution for getdns/stubby. What I hoped for from the entry of data.iana.org in /etc/hosts, is a _**reverse**_ dns-lookup via _unbound-anchor -u 72.21.81.189_ so that the the server responds to it, since stubby without trust-anchor uses /etc/resolv.conf to lookup data.iana.org and therefore fails.
/etc/hosts/ works for me, only not for that purpose, and yes in etc/nsswitch.conf I've got _files_ before _dns_

On the internet there is not much hope:
https://cheatsheet.zwischenspeicher.info/2016/05/12-2016-05-11/
https://unix.stackexchange.com/questions/329383/how-to-use-etc-hosts-in-unbound-dns-server
https://serverfault.com/questions/739829/unbound-stub-host-option-not-resolving-using-etc-hosts

I saw however a commit today with a configurable resolv.conf location in getdns as a real solution, I'll just have to wait for that 😉

**Comment by hanvinke** [comment]
I have a similar configuration :
/etc/unbound/unbound.conf
server:
   use-syslog: yes
   username: "unbound"
   directory: "/etc/unbound"
   auto-trust-anchor-file: trusted-key.key
   root-hints: "/etc/unbound/root.hints"
   ip-freebind: no
   interface: 0.0.0.0
   interface: ::0
   verbosity: 1
   do-not-query-localhost: no
   do-ip4: yes
   do-ip6: yes
   do-tcp: yes
   do-udp: yes
   use-systemd: yes
   do-daemonize: no
   ssl-upstream: yes
   ssl-port: 853
   rrset-roundrobin: yes
   module-config: "dns64 validator iterator"

forward-zone:
   name: "."
   forward-addr: 145.100.185.15@853  # dnsovertls.sinodun.com US
   forward-addr: 145.100.185.16@853  # dnsovertls1.sinodun.com US
   forward-addr: 9.9.9.9@853         # Quad9
   forward-addr: 185.49.141.37@853   # getdnsapi.net US
   forward-addr: 2001:610:1:40ba:145:100:185:15@853 # dnsovertls.sinodun.com
   forward-addr: 2001:610:1:40ba:145:100:185:16@853 #
dnsovertls1.sinodun.com
   forward-addr: 2a04:b900:0:100::38@853 # getdnsapi.net US
   forward-addr: 2620:fe::fe@853     # Quad9
   forward-ssl-upstream: yes

The only difference is that I do ssl-upstream and use unbound as a caching
server, /etc/stubby/stubby.yml:
the same stuff +

listen_addresses:
  - 127.0.0.1@5353
  -  0::1@5353

It works well, no problems at all. All that I want is to use is
*unbound-anchor* or *better zero configuration DNSSEC.*
And I hope for DANE implementation in the future.
With unbound.service I hoped for adding:







*[Unit]Description=Unbound recursive Domain Name ServerAfter=syslog.target
network.targetBefore=nss-lookup.targetWants=nss-lookup.target*

*[Service]*










*Type=simpleEnvironmentFile=-/etc/resolv.confExecStartPre=/usr/bin/unbound-checkconfExecStartPre=/usr/bin/unbound-anchor
-a /etc/unbound/trusted-key.key -c /etc/unbound/icannbundle.pem -u
72.21.81.189 -x /root-anchors/root-anchors.xml -s
/root-anchors/root-anchors.p7s -r /etc/unbound/root.hints -f
/etc/unbound/unbound.conf -P 443 -F
-vPIDFile=/run/unbound.pidExecStart=/usr/bin/unbound -dExecReload=/bin/kill
-HUP $MAINPIDRestart=always[Install]WantedBy=multi-user.target*





2017-12-12 19:48 GMT+01:00 Bruno Pagani <notifications@github.com>:

**Comment by ArchangeGabriel** [comment]
I don’t understand you configuration at all. Why do you have stubby installed if you don’t use it? Currently, you’re using unbound only.

And I’m not sure what the point of running unbound-anchor is.

**Comment by hanvinke** [comment]
I altered my previous configuration to the **unbound - unbound-anchor** combination because with the **stubby - zero configuration DNSSEC** I saw no files in /home/han/.getdns when removing/renaming the trust-anchors. But I ran into the same chicken@egg problem regarding updating the anchor with unbound-anchor instead of using zero configuration DNSSEC .

When using stubby again (preferably) I will of course remove forward-ssl-upstream and current forward-addresses etc. and put back local forwarders.

Will do a timeshift and use the new getdns version and report back.

**Comment by hanvinke** [comment]
Got stubby working again now. Could someone tell me what permissions should be set on the /home/han/.getdns folder?

**Comment by wtoorop** [comment]
@hanvinke 0700 I guess.  I'm about to do the 1.3.0 release which will have more extensive reporting so we might be better equipped to get down to issues (if you still have them).

**Comment by hanvinke** [comment]
Stubby is currently only working for me in opportunistic mode, although I think it hasn't anything to do with the configuration. 
Maybe it is related to this : https://dnsprivacy.org/jira/projects/DP/issues/DP-13?filter=allopenissues
In strict mode stubby fails.

OpenSSL> version
OpenSSL 1.1.1-dev  xx XXX xxxx

_getdns_query -K 'pin-sha256="foxZRnIh9gZpWnl+zEiKa0EJ2rdCGroMWm02gaxSc9Q="' -l T -m '@185.49.141.37~getdnsapi.net' www.google.com_

is OK. 
But 
_getdns_query -K 'pin-sha256="foxZRnIh9gZpWnl+zEiKa0EJ2rdCGroMWm02gaxSc9Q="' -l L -m '@185.49.141.37~getdnsapi.net' www.google.com_
:
**An error occurred: 301 'The context has internal deficiencies'**

**Comment by hanvinke** [comment]
# And thanks for all the support and nice holydays!

**Comment by hanvinke** [comment]
After compiling the new release 1.1.3 I also have strict mode without any problems.
The only issue I still have is that there appear no files in my home .getdns folder. But  zero configuration DNSSEC works. So great release.
