### ISSUE TITLE
Zero configuration DNSSEC fail 

### ISSUE THREAD

**Issue by andreasschulze** [getdnsapi/getdns#356]
/etc/resolv.conf point to 127.0.0.1 which is intended to be served by stubby.
But stubby without trustanchor use /etc/resolv.conf to lookup data.iana.org.

see also https://getdnsapi.net/pipermail/users/2017-November/000261.html

options:
 - use an external, public resolver with well known addresses
 - send a DCHP request. With a good chance the DHCP response contain a usable resolver

**Comment by hanvinke** [comment]
Well, that seems to be the same problem as what I had.
Stubby also has a problem with the "trust_anchors_url": <bindata of "http://data.iana.org/root-anchor".

This url actually does not exist, it should be http://data.iana.org/root-anchor**s**
Maybe if we change that first?

**Comment by wtoorop** [comment]
No @havinke, the url is truncated

@andreasschulze , my current thinking would be to have the location of resolv.conf (for meta queries) configurable.  Several existing local resolver redirectors (e.g. dnsmasque, dnssec-trigger, systemd-resolved) use a similar mechanism.  For example with systemd, the original DHCP retrieved resolvers are here: `/run/systemd/resolve/resolv.conf`

**Comment by wtoorop** [comment]
Configurable resolv.conf is in PR #362, but those are only required when doing meta queries to lookup upstream IP's.  So currently I've made it so that existing transports will be used  for this in PR #363

**Comment by wtoorop** [comment]
This issue is resolved with the 1.3.0 release
