### ISSUE TITLE
Submodules source not included in releases of getdns

### ISSUE THREAD

**Issue by KonomiKitten** [getdnsapi/getdns#369]
Hi running into this compile error:

`$ make
cd src && make default
make[1]: Entering directory '/opt/getdns/test/getdns-1.3.0/src'
../libtool --quiet --tag=CC --mode=compile gcc -std=gnu99 -I. -I. -I./util/auxiliary -I./../stubby/src -g -O2 -Wall -Wextra -D_BSD_SOURCE -D_DEFAULT_SOURCE   -Wpedantic -c ./const-info.c -o const-info.lo
make[1]: *** No rule to make target 'jsmn/jsmn.h', needed by 'convert.lo'.  Stop.
make[1]: Leaving directory '/opt/getdns/test/getdns-1.3.0/src'
Makefile:53: recipe for target 'default' failed
make: *** [default] Error 2`

~~There's no mention in the readme of jsmn being a build requirement now?~~

Seems the src/jsmn directory is empty.

~~The src/yaml directory is named src/yxml which is breaking things also...~~

The src/yxml directory is empty also.

Sorry for all the edits stubby/ is also empty.

**Comment by hanvinke** [comment]
My /src/jsmn directory is defitively not empty. So something went wrong building.

Did you download from Git and do:

git submodule update --init
libtoolize -ci 
autoreconf -fi

_**before**_ building?

**Comment by KonomiKitten** [comment]
I didn't do `git submodule update --init` because I'm using https://github.com/getdnsapi/getdns/archive/v1.3.0.tar.gz for building.

**Comment by KonomiKitten** [comment]
It may be that something like this needs to be done for releases [Proper way to release in Git with submodules](https://stackoverflow.com/a/28361740)

**Comment by hanvinke** [comment]
You're right, the tar archive doesn't contain any source files.
This should be addressed quickly and normally the responses are also very quickly.
But the maintainers have holidays too..

**Comment by KonomiKitten** [comment]
It's fine I don't expect anyone to jump at things on the holidays, hope the holidays are going well for the devs and everyone else.

**Comment by wtoorop** [comment]
Holidays are going very well, thanks :)

We create distribution tarballs including the checked out submodules and initialized autotools, and excluding some developer tools and documentation, and publish them on our website with  release notes and a PGP signature over the tarball: https://getdnsapi.net/releases/
You can find all the tarball's created this way here too: https://getdnsapi.net/dist/

We have not created the tarballs that are published on github.  This is done by github itself from tags (which I have created).  It seems impossible to turn off this "service".

**Comment by ArchangeGabriel** [comment]
Well if you look at https://github.com/getdnsapi/getdns/releases/tag/v1.3.0 for instance, the last two files are generated by GitHub but I’m not sure about the first one.

If indeed you cannot deactivate this “feature”, they are several things you could do like adding your own tarball+sig, directly on GitHub (like https://github.com/vector-im/riot-web/releases/tag/v0.13.3) or with links to https://getdnsapi.net/dist/ (as https://github.com/mattermost/desktop/releases/tag/v3.7.1). You might add the changelog there as most projects do, and you might insist on not using GitHub generated tarballs (see https://github.com/darktable-org/darktable/releases/tag/release-2.4.0 for instance).

You should also PGP sign your commits and tags. ;)

**Comment by wtoorop** [comment]
Yes, I'm experimenting with the possibilities currently :). So, I have just uploaded the first tarball you just saw.  It is the official tarball and includes all the relevant files from the submodules (and has configure generated etc.).

I have signed tags from the beginning b.t.w. and also the release tarballs.  I've have uploaded the signature for the tarball too now.

I'll try to come up with a way to keep the github automatically created releases in sync with the website.

**Comment by wtoorop** [comment]
I managed to automate synchronising the website releases with github releases with getdnsapi/getdns-website@5b21082

**Comment by ArchangeGabriel** [comment]
Awesome job! Even tagging correctly pre-release. ;D

**Comment by wtoorop** [comment]
hehe Thanks!

**Comment by KonomiKitten** [comment]
Thanks also.
