### ISSUE TITLE
DNSSEC validation fail

### ISSUE THREAD

**Issue by hanvinke** [getdnsapi/getdns#385]
In my journal log I recently notice some dropouts:

_Feb 26 13:04:50 arch.localhost systemd-resolved[486]: Using degraded feature set (UDP+EDNS0+DO) for DNS server ::1.
Feb 26 13:04:50 arch.localhost systemd-resolved[486]: Using degraded feature set (UDP+EDNS0+DO) for DNS server 127.0.0.1.
Feb 26 13:05:01 arch.localhost systemd-resolved[486]: Using degraded feature set (UDP+EDNS0) for DNS server 127.0.0.1.
Feb 26 13:05:06 arch.localhost systemd-resolved[486]: Server 127.0.0.1 does not support DNSSEC, downgrading to non-DNSSEC mode.
Feb 26 13:05:13 arch.localhost systemd-resolved[486]: Server ::1 does not support DNSSEC, downgrading to non-DNSSEC mode.
Feb 26 13:05:13 arch.localhost systemd-resolved[486]: DNSSEC validation failed for question assets-cdn.github.com IN AAAA: failed-auxiliary
Feb 26 13:05:13 arch.localhost systemd-resolved[486]: DNSSEC validation failed for question avatars2.githubusercontent.com IN AAAA: failed-auxiliary
Feb 26 13:07:10 arch.localhost systemd-resolved[486]: DNSSEC validation failed for question archlinux.org IN DS: failed-auxiliary
Feb 26 13:07:10 arch.localhost systemd-resolved[486]: DNSSEC validation failed for question archlinux.org IN SOA: failed-auxiliary
Feb 26 13:07:10 arch.localhost systemd-resolved[486]: DNSSEC validation failed for question www.archlinux.org IN A: failed-auxiliary
Feb 26 13:07:10 arch.localhost systemd-resolved[486]: DNSSEC validation failed for question www.archlinux.org IN AAAA: failed-auxiliary_

Stubby running as a systemd service.
Someone else had a similar problem on github, maybe of some interest, see https://github.com/systemd/systemd/issues/4866 .
[stubby -i.TXT](https://github.com/getdnsapi/getdns/files/1758546/stubby.-i.TXT)
I think the current resolver having the issue is Quad9, because internet.nl shows 
DNS-provider WOODYNET-1 - WoodyNet

Maybe it would also be a nice feature for stubby to determine the currently used resolver in an easy way?

Anyone else having the same issue? I am on Arch, with latest systemd 237, compiled today.

**Comment by hanvinke** [comment]
After some testing it is clearly a systemd problem. This occurred after building systemd from Git. The errors disappear when reverting back to current systemd  237.64-1 from Arch repository. It seems this might be an upcoming problem for the next systemd build.
The DNSSEC validation failures btw where independent of drivers or resolver.

**Comment by wtoorop** [comment]
Hmmm... indeed, in systemd/systemd#4866 Lennart seems on top of things, so it'll probably go away soon.
However, just to be sure I've tested too.  Apparently there is an issue with getdns' DNSSEC validating insecure NODATA responses.  I'll start working on that right now.

**Comment by wtoorop** [comment]
The issue was introduced with commit 7e103217
Resolved with commit abc69f96 , which I will merge to develop soonish

**Comment by hanvinke** [comment]
Closing this, Thanks!
