### ISSUE TITLE
Stub resolver goes into endless loop on TCP fallback

### ISSUE THREAD

**Issue by rwgroenenberg** [getdnsapi/getdns#388]
When stub resolver is configured with two TCP upstreams and both are unavailable, a single request triggers an endless loop continuously trying both upstreams as fast as possible.

This is with getdns [release/1.4.0] on CentOS 6.8.

Attached the debug output of the stub resolver.
[getdns-1.4.0-TCPloop.txt](https://github.com/getdnsapi/getdns/files/1772197/getdns-1.4.0-TCPloop.txt)

**Comment by wtoorop** [comment]
Thanks, I think we can deal with is with the new upstream management.

**Comment by rwgroenenberg** [comment]
For us this is blocking us from using 1.4.0, while we need to move away from 1.0.0 because of UDP issues.

I've done some more tests and found that the issue has been introduced with 1.2.1 (1.2.0 works Ok in this respect). I'll have a look what change caused this and whether a quick fix is possible.

**Comment by wtoorop** [comment]
Hmmm... I think it's impossible to do this without tracking the upstreams already tried.
But, because it is still a simple static array with 1.4.0, this might be relatively easy.
I'll try to do a quick fix too :)

**Comment by rwgroenenberg** [comment]
I would expect the back_off to kick in, but upstream_select_stateful() fallback to ignoring the back_off when no upstream is available otherwise. Disabling that part already improves the situation: both upstreams are then tried twice and then the back_off stops further attempts.
But indeed, keeping track of tried upstreams would be better.

**Comment by wtoorop** [comment]
There is another bug fixed (DNSSEC validation bug) which I'd like to get out quickly.  I think it would be nice to have a 1.4.1 release having at least this issue fixed, and also with the improvements from PR #386, before having a completely new upstream management .  However, I'm reluctant to introduce the new getdns_context_(get|set)_max_backoff_value () symbols, as it is still uncertain if they have meaning with the new upstream management.  That might as well have backoff based on time.
Would you mind if I would merge for a 1.4.1 release without those symbols, and having a max_backoff value of 1000 ?

**Comment by rwgroenenberg** [comment]
That's Ok. In that case I'll put the  getdns_context_(get|set)_max_backoff_value () symbols in our build on top of 1.4.1.

I'm close to having a fix for this endless loop, doing the final testing on it: it saves the index of the first tried stateful upstream and stops when it selects that one again.

**Comment by wtoorop** [comment]
:) You're ahead of me.  I was just about to try something similar (having a first_upstream in struct getdns_network_req which cannot be selected again). Thanks!

**Comment by rwgroenenberg** [comment]
Sounds very similar :)
I created a pull request for the fix

**Comment by wtoorop** [comment]
Resolved in 1.4.1
