### ISSUE TITLE
Fix the windows build to honour the tls_ca_path and tls_ca_file settings.

### ISSUE THREAD

**Issue by saradickinson** [getdnsapi/getdns#392]
Also, review code for creating the certificate store on Windows in particular the error handling and logging.

**Comment by wtoorop** [comment]
@saradickinson I just cross-compiled and tested. With me `tls_ca_path` and `tls_ca_file` settings work just fine with windows.  You can review yourself with the attached cross-compiled executables.
  - [getdns_query.exe.gz](https://github.com/getdnsapi/getdns/files/1970569/getdns_query.exe.gz)
  - [stubby.exe.gz](https://github.com/getdnsapi/getdns/files/1970570/stubby.exe.gz)
  - [getdns_server_mon.exe.gz](https://github.com/getdnsapi/getdns/files/1970564/getdns_server_mon.exe.gz)

**Comment by wtoorop** [comment]
Resolved
