### ISSUE TITLE
stubby exits when running on kernel without getrandom syscall

### ISSUE THREAD

**Issue by brent-blood** [getdnsapi/getdns#394]
I'm running stubby 1.4.1 from Debian Buster's package, though it's an LXC container on an older system with a 3.10.x kernel. I was able to get stubby to start up, but it won't respond to any queries because it is killed after ENOSYS is returned from an attempt to call getrandom(). The end of the strace output looks like:

getrandom(0xbeedc31c, 40, 0)            = -1 ENOSYS (Function not implemented)
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0
getpid()                                = 14061
gettid()                                = 14061
tgkill(14061, 14061, SIGKILL)           = ?
+++ killed by SIGKILL +++
Killed

Not knowing of this syscall before, I found an [article](https://lwn.net/Articles/711013/) on this topic with the following passage: "If an application calls getrandom() on a kernel where that system call is not supported, the glibc wrapper will simply return ENOSYS and it will be up to the application to use a fallback." That said, I found what looks like an attempt to use such a fallback in src/compat/getentropy_linux.c of getdns, but it doesn't seem to be working as intended for me.

I'm not in a spot to put a newer kernel on the system in question. Any thoughts on how I might get around this?

Otherwise, great software! I'm running it elsewhere successfully and it's totally sweet.

**Comment by hanvinke** [comment]
Which version of Python are you using? 

According to "https://lwn.net/Articles/711131/" it should be fixed in Python version 3.6 and higher:

"....I modified Python to handle ENOSYS and EPERM in getentropy(), and also modified the code to prefer getrandom() over getentropy(),"

**Comment by brent-blood** [comment]
I'll give that a try later and see where I can get. Thanks for the pointers. I realize that while it's the application's responsibility to detect ENOSYS when using that syscall that you're relying on another project for doing that. Let me hack around and if I come up with a solution I'll post back to here - I just wanted to see if this had been hit before.

**Comment by wtoorop** [comment]
@brent-blood Thanks Brent, It does look like the new version of [getentropy_linux.c](https://github.com/libressl-portable/openbsd/blob/master/src/lib/libcrypto/arc4random/getentropy_linux.c) that @hanvinke pointed out does indeed have a fallback mechanism for the ENOSYS (not implemented error).  I have adapted this version to fit.  The new version is [here](https://raw.githubusercontent.com/getdnsapi/getdns/release/1.4.2/src/compat/getentropy_linux.c). Could you try it out for me?  Thanks.

**Comment by brent-blood** [comment]
Sorry I didn't respond to this yet. I haven't had a chance to try this out yet, but I do intend to when I have some time. I'll let you know what I find.

**Comment by wtoorop** [comment]
Okay... well closing for now since I released the new file in the 1.4.2 release.
You can reopen if the issue still remains. Okay?

**Comment by brent-blood** [comment]
I tried out the latest version but still saw the same behavior. I dug in some more - and I found that I think the issue is actually coming from a call to getentropy in src/compat/arc4random.c. It looks like that library call also depends upon the getrandom syscall which is returning ENOSYS - which then causes _rs_stir to raise SIGKILL - and from the strace output, this is what causes stubby to bail.

If I comment out that raise and rebuild, the app starts functioning. So that's progress - but I also don't understand where that leaves me (this is crypto, so I'm assuming in an unsafe place).

I'm honestly not convinced that src/compat/getentropy_linux.c is being used. I added some debug code to it and rebuilt everything, but I didn't see it get built, the string I added isn't present in any of the libgetdns libraries, and the debug output isn't emitted to stderr - so it looks like the code as written is linking against getentropy in the C library rather than the one provided by the compat code.

Still digging...

**Comment by brent-blood** [comment]
I was right that getentropy_linux.c wasn't ever getting built and thus wasn't being linked in; my system (and maybe others?) was using getentropy() directly from glibc rather than from the fallback stuff. I don't understand autoconf/libtool/etc well enough to do it the right way, but I hacked things enough to get it built and linked, and now things are behaving correctly as far as I can tell. For the sake of completeness (though I figure someone who does understand those tools will do it differently/better), in src/compat/getentropy_linux.c I had to include <linux/sysctl.h> in order to have definitions for CTL_KERN, KERN_RANDOM, and RANDOM_UUID and then I had to add ${LIBOBJDIR}getentropy_linux.o to LIBOBJS in src/Makefile. Sorry I can't send you a pull request, but I'm positive what I have wouldn't be directly useful.

**Comment by wtoorop** [comment]
@brent-blood Thanks for looking into this.
The functions in `src/compat` are only to provide them when they are missing on the system.  So if you do have a `getentropy()` function already, then that is preferred over the ones provided in `src/compat`.

Do I understand correctly now that your system `getentropy()` function returns `ENOSYS` and the version from `src/compat` does not?

I noticed (and fixed on the develop branch with commit 799bd2f) the missing include also because of issue #399 b.t.w.

**Comment by hanvinke** [comment]
Maybe adding something like +AC_CHECK_FUNCS([arc4random_buf getentropy]) to configure.ac would help? See https://patchwork.freedesktop.org/patch/148277/

**Comment by hanvinke** [comment]
@brent-blood 
Your glibc, although it's probably a newer version >=2.25,  is failing because it is most likely built against the 3.10 kernel headers.

**Comment by brent-blood** [comment]
>Your glibc, although it's probably a newer version >=2.25, is failing because it is
>most likely built against the 3.10 kernel headers.

I've used terms like "failing" and such before so I apologize if that has confused you. Strictly speaking, glibc isn't "failing" - it is forming a perfectly well-formed system call for getrandom and the kernel is replying that the system call doesn't exist. That's what ENOSYS indicates. I don't believe there's anything incorrect with the behavior just described. The version of the kernel that was present when the glibc package was built should be irrelevant to what version is present when it's running - otherwise it wouldn't be safe to ever upgrade the kernel and glibc at different times, but clearly it is.

**Comment by hanvinke** [comment]
Well, what I just wanted to say that when you build against newer kernel headers, you allow glibc to
conditionally use features introduced in that kernel. If you then run stubby for instance on kernel 3.10, glibc will discover that some features are not available (and yes, system calls fail with ENOSYS).

**Comment by hanvinke** [comment]
@wtoorop 
The reason why adding the source worked earlier with issue #399 is in my opinion because at buildtime, OpenWRT is downloading the newest kernel from from http://kernel.org/. 
I don't think there is a way around a fallback with dev/random and dev/urandom for Brent-blood, since he unfortunately cannot update the kernel to 3.17. Adding the newer glibc source and building against newer kernel headers would allow building and compiling, but in the end only postpone the system calls fail at runtime.

**Comment by brent-blood** [comment]
@hanvinke I ran into the same issue as #399 and provided a solution which is why @wtoorop referred to this when he closed the other ticket. I guess I really hit two issues: 1. the routines from compat/ weren't being used when they were needed for my purposes and 2. once they were used, they were missing a header file that provided some needed definitions for enums and so they wouldn't compile.

I think we should stop talking about kernel headers and rebuilding glibc. My glibc was built with newer kernel headers (glibc is from Debian Stretch which ships with 4.9, but the kernel I'm actually using is from a Jessie system) - if anything, I'd want to recompile glibc with _older_ kernel headers so that getrandom wouldn't be provided (I'll take your word that this happens), and thus the configure script in this project wouldn't pick it up and then assume that it needed to use the compat routines. But let's be practical here: I'm not going to recompile glibc for the sake of an application when the current glibc's behavior is correct and there's a perfectly acceptable workaround present.

I agree that there's no avoiding the need for a fallback in my scenario - but I don't think anyone is suggesting otherwise. If you want to support the scenario that I'm in (and I'm not saying you have to - I'm just pointing out that it doesn't work and trying to help work out a solution). I still think the best solution for this is for stubby and getdns to always use the compat routines. They default to using getrandom via the kernel if available and only then move on to fallbacks. Trying to detect at compile time whether to use it or not by looking for the presence of getentropy() in glibc isn't always reliable since as I've shown, the presence of a syscall wrapper in the C library doesn't guarantee that the kernel has the capability to provide it at runtime. If the test actually exercised the syscall and checked what it got back, that'd be another solution - otherwise just use the compat routines all the time.

**Comment by brent-blood** [comment]
>If the test actually exercised the syscall and checked what it got back, that'd be another solution

Actually, I don't like that either as it wouldn't handle situations where binaries are provided by packages. This really should be a pure runtime check with fallbacks and not something that's determined at build time.
