### ISSUE TITLE
1.4.2 checksum mismatch

### ISSUE THREAD

**Issue by ilovezfs** [getdnsapi/getdns#398]
Fri May 11 04:01:57 2018 -0700
https://getdnsapi.net/releases/getdns-1-4-2/getdns-1.4.2.tar.gz
SHA-256 was
`a2301432a61ec6615407804018d6250df472e11e38c96bc59bb728a49a02586c`

Now
https://getdnsapi.net/releases/getdns-1-4-2/getdns-1.4.2.tar.gz
SHA-256 is
`1685b82dfe297cffc4bae08a773cdc88a3edf9a4e5a1ea27d8764bb5affc0e80`

**Comment by ilovezfs** [comment]
@saradickinson any idea what happened here? We need to rule out malicious circumstances before updating the checksum in Homebrew.

**Comment by wtoorop** [comment]
Sorry... I thought I had completed release and then noticed a few more pull requests (that happened during release candidate), so I merged those and created a new release.  I'm surprised you picked up the earlier release, as I didn't email about it and removed the first tag within 15 minutes or so...

B.t.w. I also PGP sign all tarballs and tags.

**Comment by ArchangeGabriel** [comment]
@wtoorop Well, they might have an urlwatch or something like that.

**Comment by ilovezfs** [comment]
@wtoorop thanks for explaining what happened. I have updated the checksum in https://github.com/Homebrew/homebrew-core/pull/27795.

@ArchangeGabriel yes, we run `brew livecheck` https://github.com/Homebrew/homebrew-livecheck regularly and open PRs accordingly.
