### ISSUE TITLE
getrandom ENOSYS

### ISSUE THREAD

**Issue by IanCassTwo** [getdnsapi/getdns#402]
I'm trying to run "stubby" on Ubuntu 17.10 with ARM cpu and it quits soon after receiving a DNS request with getrandom ENOSYS (Function not implemented) according to strace.

../configure --prefix=/usr/local --without-libidn --without-libidn2 --enable-stub-only --with-stubby

Linux webserver 3.10.104-184 #1 SMP PREEMPT Mon Feb 20 06:38:17 UTC 2017 armv7l armv7l armv7l GNU/Linux

Ubuntu 17.10

gcc version 7.2.0 (Ubuntu/Linaro 7.2.0-8ubuntu3.2)

**Comment by IanCassTwo** [comment]
Finally got it working. I had to edit config.h...

#undef HAVE_GETENTROPY

**Comment by wtoorop** [comment]
Thanks, this is also resolved with a recent commit 1e7da7690
