### ISSUE TITLE
An error occurred while configuring Missing dependencies: libidn

### ISSUE THREAD

**Issue by rdbox** [getdnsapi/getdns#403]
I tried all the settings that are written in different articles does not help me this.
When configuring, run this command
```
root@user1:~/getdns/build# ../configure --prefix=/usr/local/bin --enable-stub-only --with-stubby --without-libidn2
```
**error**
```
configure: WARNING: libcheck not found or usable; unit tests will not be compiled and run
configure: Default trust anchor: /usr/local/bin/etc/unbound/getdns-root.key
configure: Checking for dependency libyaml
checking for yaml_parser_parse in -lyaml... yes
configure: error: Missing dependencies: libidn
```
if I change the argument at the end to such **--without-libidn**
```
configure: Checking for dependency libyaml
checking for yaml_parser_parse in -lyaml... yes
configure: error: Missing dependencies: libidn2 (version 2.0.0 or higher)
```

what to do?
I need to install and work with stubby !!!

**Comment by saradickinson** [comment]
You need to use both --without_libidn and --without-lidbin2 on the command line if you want to compile without either!

**Comment by saradickinson** [comment]
NOTING:
- The README.md file for getdns does indeed need updating!
- The README.md for stubby (the last section) already contains the correct instructions. I've just fixed the linux build instructions on dnsprivacy.org
Was there anywhere else you spotting this being wrong in documentation?

**Comment by rdbox** [comment]
When ```--enable-stub-only```, ```--without-libidn``` and ```--without-libidn2``` options are used, getdns has only one dependency left, which is OpenSSL.

Unfortunately I did not understand that I should simultaneously use 2 parameters

**Comment by saradickinson** [comment]
So did you get stubby running OK from the command line? If so then did you take a look at this page: https://dnsprivacy.org/wiki/display/DP/Running+as+a+service+on+*nix
for how to set it up as a service?

**Comment by rdbox** [comment]
```make```
```make install```
after these commands appeared this message

```
make[1]: Leaving directory '/root/getdns/build/doc'
***
***  !!! IMPORTANT !!!!
***
***  From release 1.2.0, getdns comes with built-in DNSSEC
***  trust anchor management.  External trust anchor management,
***  for example with unbound-anchor, is no longer necessary
***  and no longer recommended.
***
***  Previously installed trust anchors, in the default location -
***
***        /usr/local/bin/etc/unbound/getdns-root.key
***
***  - will be preferred and used for DNSSEC validation, however
***  getdns will fallback to trust-anchors obtained via built-in
***  trust anchor management when the anchors from the default
***  location fail to validate the root DNSKEY rrset.
***
***  To prevent expired DNSSEC trust anchors to be used for
***  validation, we strongly recommend removing the trust anchors
***  on the default location when there is no active external
***  trust anchor management keeping it up-to-date.
```
