### ISSUE TITLE
Oracle Linux 7, Unbreakable Kernel 4 Service will not start

### ISSUE THREAD

**Issue by scoobaspeaz** [getdnsapi/getdns#404]
I have found an issue that where when using Oracle Linux 7 with kernel 4.1.12-124.16.4.el7uek.x86_64 will cause the below to occur.  The resolution was to fall back to a non UEK at version 3.10.0-862.3.3.el7.x86_64

Issue when using the UEK 4:

systemctl status stubby
● stubby.service - stubby DNS resolver
   Loaded: loaded (/usr/lib/systemd/system/stubby.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2018-06-20 18:08:08 EDT; 2min 22s ago
  Process: 3236 ExecStart=/usr/bin/stubby (code=exited, status=218/CAPABILITIES)
 Main PID: 3236 (code=exited, status=218/CAPABILITIES)

Jun 20 18:08:08 hotdog.subspeaz.net systemd[1]: Started stubby DNS resolver.
Jun 20 18:08:08 hotdog.subspeaz.net systemd[1]: Starting stubby DNS resolver...
Jun 20 18:08:08 hotdog.subspeaz.net systemd[1]: stubby.service: main process exited, code=exited, status=218/CAPABILITIES
Jun 20 18:08:08 hotdog.subspeaz.net systemd[1]: Unit stubby.service entered failed state.
Jun 20 18:08:08 hotdog.subspeaz.net systemd[1]: stubby.service failed.

Works fine when I fail back to a non UEK 3 kernel:

systemctl status stubby
● stubby.service - stubby DNS resolver
   Loaded: loaded (/usr/lib/systemd/system/stubby.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2018-06-20 18:19:55 EDT; 25min ago
 Main PID: 671 (stubby)
   CGroup: /system.slice/stubby.service
           └─671 /usr/bin/stubby

Jun 20 18:19:55 hotdog.subspeaz.net systemd[1]: Started stubby DNS resolver.
Jun 20 18:19:55 hotdog.subspeaz.net systemd[1]: Starting stubby DNS resolver...
Jun 20 18:19:56 hotdog.subspeaz.net stubby[671]: [22:19:56.331932] STUBBY: Read config from file /etc/stubby/stubby.yml
Jun 20 18:19:56 hotdog.subspeaz.net stubby[671]: [22:19:56.335455] STUBBY: DNSSEC Validation is OFF
Jun 20 18:19:56 hotdog.subspeaz.net stubby[671]: [22:19:56.335505] STUBBY: Transport list is:
Jun 20 18:19:56 hotdog.subspeaz.net stubby[671]: [22:19:56.335554] STUBBY:   - TLS
Jun 20 18:19:56 hotdog.subspeaz.net stubby[671]: [22:19:56.335606] STUBBY: Privacy Usage Profile is Strict (Authentication required)
Jun 20 18:19:56 hotdog.subspeaz.net stubby[671]: [22:19:56.335702] STUBBY: (NOTE a Strict Profile only applies when TLS is the ONLY transport!!)
Jun 20 18:19:56 hotdog.subspeaz.net stubby[671]: [22:19:56.335748] STUBBY: Starting DAEMON....

**Comment by scoobaspeaz** [comment]
Version of getdns

[root@hotdog stubby]# rpm -qa |grep getdns
getdns-1.4.2-1.el7.x86_64

**Comment by scoobaspeaz** [comment]
Anyone have any idea why this happens? I'd like to fix it if i could.

**Comment by scoobaspeaz** [comment]
systemctl stubby.service
Unknown operation 'stubby.service'.
[root@utility ~]# systemctl status stubby.service
● stubby.service - stubby DNS resolver
   Loaded: loaded (/usr/lib/systemd/system/stubby.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2018-08-18 05:33:51 EDT; 1 weeks 2 days ago
 Main PID: 605 (code=exited, status=218/CAPABILITIES)

**Comment by scoobaspeaz** [comment]
Kernel being used:  4.1.12-124.18.6.el7uek.x86_64

**Comment by scoobaspeaz** [comment]
Alright so troubleshooting this it appears with the Oracle Unbreakable Kernel 4 the issue lies in stubby being able to run as the stubby user.  At first i thought it was just port 53 (since its less than 1024) so i changed it in stubby.yml to be 8053 and still had the same result. 

I can get this to start one of two ways:
1. comment out all 3 below from /usr/lib/systemd/system/stubb.service and run it as root:
AmbientCapabilities=CAP_NET_BIND_SERVICE
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
User=stubby

2. Change the port to something higher than 1024 such as 8053 and start it with the following two commented out:
AmbientCapabilities=CAP_NET_BIND_SERVICE
CapabilityBoundingSet=CAP_NET_BIND_SERVICE

**Comment by hanvinke** [comment]
I don't use RHEL personally but this might be of some help.
According to Red Hat there is support for Ambient Capabilities starting from RHEL version 7.3.
This update adds support for ambient capabilities to the kernel.

Is SELinux enabled? You can check either with:
[root@centos7 ~]# getenforce
Enforcing
[root@centos7 ~]# sestatus

You can use ‘setenforce 0’ to swap to permissive mode, or ‘setenforce 1’ to swap to enforcing mode.
Maybe with SElinux being only permissive stubby will run with Ambient Capabilities.

**Comment by wtoorop** [comment]
@scoobaspeaz did @hanvinke 's advice help you?
I'm closing this ticket. Let me know if there is anything you think we could do to help.
