### ISSUE TITLE
how to run stubby as a service

### ISSUE THREAD

**Issue by rdbox** [getdnsapi/getdns#405]
I re-read a lot of instructions and did not understand how to make it so that stubby would start automatically after the system boot 
**I want to make stubby work with systemctl**

Here this command I did build configure stubby
```
../configure --prefix=/usr/local/bin --enable-stub-only --with-stubby --without-libidn2 --without-libidn --enable-debug-stub  --with-piddir=/var/log/
```

**Comment by saradickinson** [comment]
Have you tried using the instructions in this directory?
https://github.com/getdnsapi/stubby/tree/develop/systemd

**Comment by wtoorop** [comment]
Closing because communication stalled
