### ISSUE TITLE
make test fails on gentoo package because network access is needed

### ISSUE THREAD

**Issue by CaseOf** [getdnsapi/getdns#407]
Hello,
I'm maintaining [`net-dns/getdns`](https://packages.gentoo.org/packages/net-dns/getdns) package on Gentoo and [a bug report](https://bugs.gentoo.org/661760) was submitted explaining that `make test` fails on unstable system keyword.
I would like help to understand what could be causing this failure to solve it.
Sincerely,
CaseOf.

**Comment by saradickinson** [comment]
Hi, the expert on the unit tests is currently on vacation but I do know that the tests require network connectivity and perform DNS lookups so if there are problems with the network or the local resolver it can effect the tests..... With a quick look it seems like some of those lookups failed in this case. 
@wtoorop maybe we should have an option to manage this...

**Comment by CaseOf** [comment]
I think now that you mention about network access for tests, that it is related to the following rule: https://devmanual.gentoo.org/ebuild-writing/functions/src_test/index.html#tests-that-require-network-or-service-access

**Comment by saradickinson** [comment]
@CaseOf I think that would do it.... @wtoorop is back in the office next week so we'll discuss this with him then.

**Comment by wtoorop** [comment]
Upcoming 1.6.0 release candidate will have a script that skips the tests that require networking in `src/test/tpkg/run-offline-only.sh`.

**Comment by wtoorop** [comment]
There is a workaround in getdns-1.6.0
