### ISSUE TITLE
ENGINE code is being used outside of GOST support.

### ISSUE THREAD

**Issue by jonathanunderwood** [getdnsapi/getdns#416]
Related to #401. 

@neheb reports that "ENGINE code is being used outside of GOST support. This is not correct."  https://github.com/openwrt/packages/pull/7522

I have to admit, I don't understand what (s)he actually means with this, but I thought it would be a good idea to report upstream anyway.

**Comment by wtoorop** [comment]
Ok, so closing. Let me know if that's wrong...
