### ISSUE TITLE
DNSSEC Validation Fails

### ISSUE THREAD

**Issue by bonedaddy** [getdnsapi/getdns#425]
# Info

I'm getting repeated DNSSEC validation failures all of a sudden, which is breaking stubby. It seems to be related to https://github.com/getdnsapi/getdns/issues/385

# Versions

Stubby: `0.2.2`
OS: `Pop!_OS (aka, Ubuntu 18.04.4 LTS)`
systemd:
```
systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```
I installed with `sudo apt install stubby`

# Logs

```
Apr  8 16:54:47 dark systemd-resolved[24015]: DNSSEC validation failed for question github.com IN AAAA: incompatible-server
Apr  8 16:55:31 dark systemd-resolved[24015]: DNSSEC validation failed for question clients4.google.com IN A: incompatible-server
Apr  8 16:55:31 dark systemd-resolved[24015]: DNSSEC validation failed for question clients4.google.com IN AAAA: incompatible-server
Apr  8 16:55:31 dark systemd-resolved[24015]: DNSSEC validation failed for question clients4.google.com IN A: incompatible-server
Apr  8 16:55:31 dark systemd-resolved[24015]: DNSSEC validation failed for question clients4.google.com IN AAAA: incompatible-server
Apr  8 16:55:31 dark systemd-resolved[24015]: DNSSEC validation failed for question clients4.google.com IN A: incompatible-server
Apr  8 16:55:31 dark systemd-resolved[24015]: DNSSEC validation failed for question clients4.google.com IN AAAA: incompatible-server
Apr  8 16:55:31 dark systemd-resolved[24015]: DNSSEC validation failed for question clients4.google.com IN A: incompatible-server
Apr  8 16:55:31 dark systemd-resolved[24015]: DNSSEC validation failed for question clients4.google.com IN AAAA: incompatible-server
```

# Configuration

upstream_recursive_servers
```
dns_transport_list:
  - GETDNS_TRANSPORT_TLS

tls_authentication: GETDNS_AUTHENTICATION_REQUIRED

resolution_type: GETDNS_RESOLUTION_STUB

upstream_recursive_servers:
  - address_data: 8.8.8.8
    tls_auth_name: "dns.google"
  - address_data: 8.8.4.4
    tls_auth_name: "dns.google"
  - address_data: 1.1.1.1
    tls_auth_name: "cloudflare-dns.com"
  - address_data: 1.0.0.1
    tls_auth_name: "cloudflare-dns.com"
  - address_data: 145.100.185.15
    tls_auth_name: "dnsovertls.sinodun.com"
    tls_pubkey_pinset:
      - digest: "sha256"
        value: 62lKu9HsDVbyiPenApnc4sfmSYTHOVfFgL3pyB+cBL4=
  - address_data: 145.100.185.16
    tls_auth_name: "dnsovertls1.sinodun.com"
    tls_pubkey_pinset:
      - digest: "sha256"
        value: cE2ecALeE5B+urJhDrJlVFmf38cJLAvqekONvjvpqUA=
# The getdnsapi.net server
  - address_data: 185.49.141.37
    tls_auth_name: "getdnsapi.net"
    tls_pubkey_pinset:
      - digest: "sha256"
        value: foxZRnIh9gZpWnl+zEiKa0EJ2rdCGroMWm02gaxSc9Q=
# IPv6 addresses
# The Surfnet/Sinodun servers
  - address_data: 2606:4700:4700::1111
    tls_auth_name: "cloudflare-dns.com"
  - address_data: 2606:4700:4700::1001
    tls_auth_name: "cloudflare-dns.com"
  - address_data: 2001:610:1:40ba:145:100:185:15
    tls_auth_name: "dnsovertls.sinodun.com"
    tls_pubkey_pinset:
      - digest: "sha256"
        value: 62lKu9HsDVbyiPenApnc4sfmSYTHOVfFgL3pyB+cBL4=
  - address_data: 2001:610:1:40ba:145:100:185:16
    tls_auth_name: "dnsovertls1.sinodun.com"
    tls_pubkey_pinset:
      - digest: "sha256"
        value: cE2ecALeE5B+urJhDrJlVFmf38cJLAvqekONvjvpqUA=
# The getdnsapi.net server
  - address_data: 2a04:b900:0:100::38
    tls_auth_name: "getdnsapi.net"
    tls_pubkey_pinset:
      - digest: "sha256"
        value: foxZRnIh9gZpWnl+zEiKa0EJ2rdCGroMWm02gaxSc9Q=
```

**Comment by hanvinke** [comment]
Maybe a stupid question but since your system is called "dark systemd-resolved", what is the status of systemd-resolved?

**Comment by postables** [comment]
`dark systemd-resolved[24015]`  is just log output from syslog this means host `dark` process `systemd-resolved` pid `24015`

`systemd-resolved` is active. The only way I was able to work around this issue is by placing `dnsmasq` in-front of stubby to act as a cache

**Comment by hanvinke** [comment]
Yes, thanks for the responds. But why are you using systemd-resolved when you have stubby?

You can set f.i. NetworkManager to DHCP only. Stubby takes care of the rest. Also in /etc/resolv.conf you don't need to add the nameservers. Even no need to add them to /etc/hosts.
Stubby is also able to use nscd. Just enable with sudo systemctl enable nscd, and check with sudo nscd -g
I suppose you have the following settings: 

/etc/dnsmasq.conf:

no-resolv
proxy-dnssec
server=::1#53000
server=127.0.0.1#53000
listen-address=::1,127.0.0.1

**Comment by hanvinke** [comment]
The problem with systemd-resolved is that it has only limited caching capacity and it solely supports opportunistic DNS.  Stubby on the contrary can also do Strict mode.
With systemd-resolved also active as a resolver this probably means you can only do Opportunistic mode:
tls_authentication:GETDNS_AUTHENTICATION_NONE

**Comment by hanvinke** [comment]
I have installed and configured dnsmasq with stubby. The archwiki seems to be not quite correct, sorry!

It says "listen-address=::1,127.0.0.1" but that is incorrect in my view, dnsmasq should simply listen to port 53 (which it standard and it already does). Also "proxy-dnssec" doesn't seem to exist, probably deprecated. Just leave #dnssec uncommented.

My dnsmasq.conf:
# If you don't want dnsmasq to read /etc/resolv.conf or any other
# file, getting its servers from this file instead (see below), then
# uncomment this.
no-resolv

# and this sets the source (ie local) address used to talk to
# 10.1.2.3 to 192.168.1.1 port 55 (there must be an interface with that
# IP on the machine, obviously).
# server=10.1.2.3@192.168.1.1#55
server=127.0.0.1#53000
server=::1#53000

In NetworkManager I would also add the dns servers 127.0.0.1 and ::1.

**Comment by hanvinke** [comment]
Correction: The archwiki was correct, only I was wrong. 

man dnsmasq.conf shows --proxy-dnssec:

"Copy the DNSSEC Authenticated Data bit from upstream servers to downstream clients and cache it.  This is an alternative to having dnsmasq validate DNSSEC, but it depends on the security of the network between dnsmasq and the upstream servers, and the trustworthiness of the upstream servers." See also https://wiki.archlinux.org/index.php/dnsmasq

**Comment by wtoorop** [comment]
@bonedaddy Was your `systemd-resolved` validating the DNSSEC data coming from stubby?
I have not tried that myself, but that "should" work yes. I have seen setups that use Unbound and dnsmasq in this way.

For now I will close the ticket, please reopen if you think there is anything we can do improve things.
