### ISSUE TITLE
`make stubby` doesn't work

### ISSUE THREAD

**Issue by yegle** [getdnsapi/getdns#429]
Run `make stubby` doesn't work because there's a stubby directory.

**Comment by saradickinson** [comment]
Can you please provide a console log of your whole build process (starting with cloning the git repo)?

**Comment by yegle** [comment]
Sorry for the delay. I was referring to the gz'ed source code

```
wget https://getdnsapi.net/dist/getdns-1.5.2.tar.gz
tar xvf getdns-1.5.2.tar.gz 
cd getdns-1.5.2
./configure
```

Then I get the following error:
```
$ make stubby
make: Nothing to be done for 'stubby'.
```

**Comment by yegle** [comment]
This works:

```
cd src && make stubby
```

**Comment by yegle** [comment]
Hmm I think I was mistaken. I should've just add `--with-stubby` and do `make && make install`.
