### ISSUE TITLE
Systemd: after inactivity stubby stops resolving

### ISSUE THREAD

**Issue by hanvinke** [getdnsapi/getdns#431]
When with the current configuration (enabled DNSSEC) using firefox, stubby works excellent in the beginning. But after some inactivity the "signal" is lost. I have to manually restart stubby then. 
Looking for the cause of this I did a sudo strace stubby afterwards. Then there is a lot of information, but I saw some messages about "bind" not being able to reuse the 127.0.0.1 IP-address. Maybe that is the cause for the degradation?! In systemd there is a possibility to reuse the port, but only when using a socket. So I tried that and it seems to work well. 

My stubby socket looks like this: 
[stubby.socket.TXT](https://github.com/getdnsapi/getdns/files/3355989/stubby.socket.TXT)

Stubby.service:
[stubby.service.TXT](https://github.com/getdnsapi/getdns/files/3356002/stubby.service.TXT)

The option "ReusePort" has the following advantages:

For TCP sockets, this option allows accept load distribu‐
              tion in a multi-threaded server to be improved by using a dis‐
              tinct listener socket for each thread.  This provides improved
              load distribution as compared to traditional techniques such
              using a single accepting thread that distributes connec‐
              tions, or having multiple threads that compete to accept
              from the same socket.

 For UDP sockets, the use of this option can provide better
              distribution of incoming datagrams to multiple processes (or
              threads) as compared to the traditional technique of having
              multiple processes compete to receive datagrams on the same
              socket.

There are also some other benefits by using a socket activation of stubby.
For instance when you wish to improve latencies and robustness you normally have to do something like:
sudo sysctl -w \
net.ipv4.tcp_fastopen=3 \
net.ipv4.tcp_tw_reuse=1 \
net.ipv4.tcp_slow_start_after_idle=0 \
net.ipv4.tcp_keepalive_time=60 \
net.ipv4.tcp_keepalive_intvl=10 \
net.ipv4.tcp_keepalive_probes=6 \
net.ipv4.tcp_rfc1337=1
etc.

But with a socket these temporary improvements can be made permanent as well.

There is probably a way to improve the steadiness of stubby in another way, but maybe simply applying a socket is easier?  I personally don't think stubby needs an update here.

**Comment by wtoorop** [comment]
Interesting! Thanks

**Comment by hanvinke** [comment]
While testing I noticed that strace also with the socket in use gives me a single message as:

"bind(4, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("127.0.0.1")}, 16) = -1 EADDRINUSE (Adres is al in gebruik)"

This is regardless even when stubby is not configured in stubby.yml to listen to port 127.0.0.1
I am testing now with /etc/resolv.conf "options single-request-reopen", maybe that has some potential.

While testing i also noticed (when having ::1 instead of 0::1 under listen_addresses:) another curious error message:
socket(AF_INET, SOCK_DGRAM, IPPROTO_UDP) = -1 EMFILE (Te veel open bestanden)

**Comment by wtoorop** [comment]
I know, the yaml processing needs improvement at some point... Now it is just a simple syntactical conversion to json, which hampers some of the primitives.

**Comment by hanvinke** [comment]
Thanks for the response! I will continue to investigate..

**Comment by hanvinke** [comment]
I tracked the possible cause. My router had a small firmware update and my ipv6 settings had disappeared. So basically I was not able to reach ipv6 addresses both with and without systemd socket activation. I therefore set my router's ipv6 DNS server back to 0::1 and voila!
Nevertheless I will personally stay using socket activation, although the option "ReusePort=yes" actually didn't do much. Sorry consuming your precious time, I am closing this thread.
