### ISSUE TITLE
answer_ipv4_address

### ISSUE THREAD

**Issue by neildunbar** [getdnsapi/getdns#432]
(Probably more of a documentation comprehension issue on my part, but here goes)

I'm trying to write some code using getdns which is looking for the contents of the `replies_tree` field `answer_ipv4_address`. Now, granted, the spec does state that such a field is optional, thus not guaranteed to be there at all - but my question is: does the current implementation actually populate that field, and if so - where?

Thanks,

Neil

**Comment by saradickinson** [comment]
@wtoorop can correct me, but to my knowledge the current implementation does not populate that field.

One option is to use the `return_call_reporting` extension (not part of the official API) which provides information about the resolution step, for example with a UDP query to 8.8.8.8:

`   "call_reporting":
  [
    {
      "query_name": <bindata for example.com.>,
      "query_to":
      {
        "address_data": <bindata for 8.8.8.8>,
        "address_type": <bindata of "IPv4">
      },
      "query_type": GETDNS_RRTYPE_AAAA,
      "resolution_type": GETDNS_RESOLUTION_STUB,
      "run_time/ms": 6,
      "transport": GETDNS_TRANSPORT_UDP,
      "udp_responses_for_this_upstream": 2,
      "udp_timeouts_for_this_upstream": 0
    },
    {
      "query_name": <bindata for example.com.>,
      "query_to":
      {
        "address_data": <bindata for 8.8.8.8>,
        "address_type": <bindata of "IPv4">
      },
      "query_type": GETDNS_RRTYPE_A,
      "resolution_type": GETDNS_RESOLUTION_STUB,
      "run_time/ms": 6,
      "transport": GETDNS_TRANSPORT_UDP,
      "udp_responses_for_this_upstream": 2,
      "udp_timeouts_for_this_upstream": 0
    }
  ],
`

**Comment by wtoorop** [comment]
Correct, we seem to have missed these fields completely. For completeness I suppose we should implement those.
