### ISSUE TITLE
'Nettle' small compilation error with getdns-1.6.0-rc.1

### ISSUE THREAD

**Issue by hanvinke** [getdnsapi/getdns#458]
Now running the new release candidate with gnuTLS. 

With nettle I ran into some compilation error:
"/getdns-1.6.0-rc.1/src/tls/val_secalgo.c:1729:36: fout: ‘nettle_secp_256r1’ undeclared (first use in this function); did you mean ‘nettle_get_secp_256r1’?"
After changing that it ran well.

BTW only nettle version 3.6 supports ED448 signatures.

**Comment by banburybill** [comment]
Thanks. PR incoming. Note that the use of e.g. `&nettle_secp_256r1` needs to be replaced by `nettle_get_secp_256r1()`,  not `&nettle_get_secp_256r1`.

I've filed a separate issue to add support for ED448 when using Nettle.
