### ISSUE TITLE
1.6.0: Build failure under FreeBSD

### ISSUE THREAD

**Issue by zi0r** [getdnsapi/getdns#469]
After running 'cmake .':

-- Looking for arc4random_uniform - found
-- Found OpenSSL: /usr/lib/libcrypto.so (found version "1.0.2o")  
-- Found Libunbound: -pthread;/usr/lib/libssl.so;/usr/lib/libcrypto.so;/usr/local/lib/libunbound.so (found suitable version "1.9.3", minimum required is "1.5.9") 
-- Looking for unbound-event.h
-- Looking for unbound-event.h - not found
-- Looking for ub_ctx_create_ub_event
-- Looking for ub_ctx_create_ub_event - not found
-- Looking for ub_ctx_set_stub
-- Looking for ub_ctx_set_stub - not found
-- Performing Test STRPTIME_WORKS
-- Performing Test STRPTIME_WORKS - Success
-- Looking for netinet/tcp.h
-- Looking for netinet/tcp.h - found
-- Looking for TCP_FASTOPEN
-- Looking for TCP_FASTOPEN - found
-- Looking for TCP_FASTOPEN_CONNECT
-- Looking for TCP_FASTOPEN_CONNECT - not found
-- Looking for MSG_FASTOPEN
-- Looking for MSG_FASTOPEN - not found
-- Found Libev: /usr/local/lib/libev.so  
-- Found Libevent2: /usr/local/lib/libevent_core.so (found version "2.1.11-stable") 
-- Found Libuv: /usr/local/lib/libuv.so (found version "1.32.0") 
CMake Error at /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Check (missing: CHECK_LIBRARIES CHECK_INCLUDE_DIR) (Required
  is at least version "0.9.6")
Call Stack (most recent call first):
  /usr/local/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindCheck.cmake:92 (find_package_handle_standard_args)
  CMakeLists.txt:937 (find_package)

**Comment by zi0r** [comment]
This occurred while trying to update the port from v1.5.2 to v1.6.0

**Comment by hanvinke** [comment]
No package 'check' for BSD?

https://libcheck.github.io/check/

"Check works on many UNIX compatible environments, such as GNU/Linux, GNU/Hurd, BSD, and Mac OSX."

**Comment by zi0r** [comment]
My bad, thank you.  I did not parse "Could NOT find Check" as a missing package.  E_COFFEE.
