### ISSUE TITLE
CMake fails to locate Check library

### ISSUE THREAD

**Issue by jonathanunderwood** [getdnsapi/getdns#481]
Building getdns 1.6.0 against OpenWRT 19.07 I see the following build failure, even though libcheck is installed:

```
CMake Error at /home/build/build_dir/staging_dir/host/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Check (missing: CHECK_LIBRARIES CHECK_INCLUDE_DIR) (Required
  is at least version "0.9.6")
Call Stack (most recent call first):
  /home/build/build_dir/staging_dir/host/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindCheck.cmake:92 (find_package_handle_standard_args)
  CMakeLists.txt:937 (find_package)
```

Full build log: 

https://circleci.com/api/v1.1/project/github/openwrt/packages/9259/output/105/0?file=true&allocation-id=5f01ba6369d8dd5573e4a200-0-build%2F76B0D9DB

**Comment by jonathanunderwood** [comment]
@banburybill wondering if you have any insight here - I know you've done a lot with the CMake buildsystem recently.

**Comment by jonathanunderwood** [comment]
Also seen with gentoo: https://bugs.gentoo.org/703886

**Comment by banburybill** [comment]
Any chance you could share the record of the check from CMakeFiles/CMakeOutput.log and CMakeError.log?

**Comment by jonathanunderwood** [comment]
Turns out that, actually, I didn't have check installed in the build environment, when I thought I did. Ensuring that was present fixes things. Apologies for the noise. Will close.
