### ISSUE TITLE
Completely bypassing OS resolver

### ISSUE THREAD

**Issue by ncoder-1** [getdnsapi/getdns#483]
Hi,

If I want to completely bypass the OS resolver and use `getdns` to resolve queries for my application internally (such as using my own selected DNS servers instead of `/etc/resolv.conf` or OS/DHCP provided ones), am I understanding correctly that setting `set_from_os `to `0` and using `getdns_context_set_upstream_recursive_servers` is the right way or am I missing something?

If I'd like to go one step further and use DoT, would `getdns` and setting `GETDNS_TRANSPORT_TLS` allow me to internally resolve over DoT (almost like running an internal `stubby` resolver)?

Thanks!

**Comment by saradickinson** [comment]
@ncoder-1 You are correct about the settings and their effect. One further thing you probably want to configure...
when you create the upstream, also specify the ```tls_auth_name``` if the server you want to use publishes it and then you can also set ```tls_authentication: GETDNS_AUTHENTICATION_REQUIRED``` to ensure getdns will  authenticate the certificate provided by the upstream.

**Comment by ncoder-1** [comment]
@saradickinson thanks!

**Comment by ncoder-1** [comment]
@saradickinson, I got what I wanted working but I'm having issue setting the `tls_auth_name` for the upstream.

Here is what I'm doing to add the `address_data`:

 ```
std::vector<std::string> resolvers{"1.1.1.1", "1.0.0.1"};

  getdns_dict* resolver_dict = getdns_dict_create();
  getdns_list* resolver_list = getdns_list_create();

  // memory leak...
  for (int i = 0; i < resolvers.size(); i++) {
    r = getdns_str2dict(resolvers[i].c_str(), &resolver_dict);
    r = getdns_list_set_dict(resolver_list, i, resolver_dict);
  }

//code

else if ((r = getdns_context_set_upstream_recursive_servers(context, resolver_list)))
    fprintf(stderr, "Could not set upstream recursive servers.\n");
```

Can you point me in the right direction on adding a `tls_auth_name` such as `cloudflare-dns.com` in the `resolver_list` (which I assume is where it goes)?

**Comment by ncoder-1** [comment]
Responding to myself in case someone else finds themselves in that scenario, fix is:

`std::vector<std::string> resolvers{"1.1.1.1~cloudflare-dns.com", "1.0.0.1~cloudflare-dns.com"};`

**Comment by saradickinson** [comment]
That is one neat way to do it :-) It does rely on custom processing developed for the command line tool ```getdns_query`` though. 

For reference, the documentation for the upstream structure can be found here:
https://getdnsapi.net/doxygen/group__getdns__context.html#ga248a2a426cab71d8d12b093e487118af

For upstreams with more than just an IP address, create a ```getdns_dict``` for each list entry then set the (in this case) bindata element for the specific item. Pseudo code for the tls_auth_name which holds a string would be something like:
```
        getdns_dict *resolver;
	getdns_bindata address_data = { 4, (void *)"\x01\x01\x01\x01" };

        getdns_dict_util_set_string(resolver, "address_type", "IPv4");
        getdns_dict_set_bindata(resolver, "address_data", &address_data);
	getdns_dict_util_set_string(resolver, "tls_auth_name", "cloudflare-dns.com");
```

**Comment by Masklixin** [comment]
> Responding to myself in case someone else finds themselves in that scenario, fix is (with `for` loop removed):
> 
> ```
> else if ((r = getdns_context_set_tls_authentication(context, GETDNS_AUTHENTICATION_REQUIRED)))
>    fprintf(stderr, "Could not set TLS AUTH REQUIRED.\n");
> 
> else if ((r = getdns_str2list("[1.1.1.1~cloudflare-dns.com,1.0.0.1~cloudflare-dns.com]", &resolver_list)))
>   fprintf(stderr, "Error converting upstreams list.\n");
> 
> else if ((r = getdns_context_set_upstream_recursive_servers(context, resolver_list)))
>    fprintf(stderr, "Could not set upstream recursive servers.\n");
> ```

Hi,I want to query multiple specified DNS servers at the same time. I used your method, but it only sends to the first one in the list. Do you know why? For example, the following code will only send queries to 1.1.1.1
`else if ((r = getdns_str2list("[1.1.1.1,1.0.0.1]", &resolver_list)))
  fprintf(stderr, "Error converting upstreams list.\n");

else if ((r = getdns_context_set_upstream_recursive_servers(context, resolver_list)))
   fprintf(stderr, "Could not set upstream recursive servers.\n");

ret = getdns_general_sync(context, service_name,  GETDNS_RRTYPE_A,NULL,&response);
    if (ret != GETDNS_RETURN_GOOD) {
        OssUserLogError("Query1failed: %s\n", getdns_get_errorstr_by_id(ret));
        goto cleanup;
    }` @ncoder-1 @saradickinson

**Comment by saradickinson** [comment]
Hi there - you are using the synchronous `getdns_general_sync` method here. If you want to do multiple queries in parallel, you need to use the asynchronous model provided but `getdns` - please read the [Examples](https://getdnsapi.net/blog/categories/basic/) page on the `getdns` website which goes into detail, particularly the section `Doing multiple requests asynchronously`!
