### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by maciejsszmigiero** [getdnsapi/getdns#502]
Hi @saradickinson @wtoorop 

The last getdns release was more than a year ago.

Since that time there were a few new commits and a few new pull requests opened,
any plans for making a new release?

Thanks

**Comment by saradickinson** [comment]
@wtoorop and I just met and we should have a new `getdns` release candidate ready next week

**Comment by maciejsszmigiero** [comment]
Thanks!

**Comment by maciejsszmigiero** [comment]
Closing since 1.7.0 was released.
