### ISSUE TITLE
system and per-user configuration files

### ISSUE THREAD

**Issue by glenwiley** [getdnsapi/getdns#51]
It would be good to support an optional system wide and per user configuration file that affects the run-time performance of the getdns library.  If the files do not exist then the library runs the way it is currently designed to.

The system wide configuration would be in /etc/getdns.conf and the per user file would be ~/.getdns.conf

Some of the elements addressed in the configuration files include:
- special behavior for particular zones, forwarding, etc.
- whether to accept dhcp provided resolvers or override with manually specified resolvers
- default settings in the context such as stub vs. recursive mode for the library
- cache behavior - whether to share with the system or per user, another issue addresses this in more detail

**Comment by wtoorop** [comment]
Both stubby and getdns_query have this option.  So allthough not implemented in the library, it is trivial to implement this from an application using the library.
