### ISSUE TITLE
Broken trust anchor files are silently ignored

### ISSUE THREAD

**Issue by bortzmeyer** [getdnsapi/getdns#536]
```
./getdns_query  @127.0.0.1:3553 +dnssec_return_status -f /etc/modules -s -D test SOA
```

(No error message displayed, despite the fact that `/etc/modules` has an unexpected syntax...)

**Comment by bortzmeyer** [comment]
Thanks. Now, if I may, what is the expected format of this file? I don't find it in the documentations.

**Comment by wtoorop** [comment]
> Thanks. Now, if I may, what is the expected format of this file? I don't find it in the documentations.

It expects resource records in presentation format. DS and DNSKEY records will be used as trust anchors for their owner domain name. I suspect that missing DS and DNSKEY resource records will be ignored. The -f option to getdns_query is basically a combination of [getdns_fp2rr_list()](https://getdnsapi.net/doxygen/group__UDNSDataConversionFunctions.html#ga7fa5820aa12afbb14dc83fd69b6e08c9) and [getdns_context_set_dnssec_trust_anchors()](https://getdnsapi.net/doxygen/group__getdns__context.html#gadde7178a1df81558e6217616689fe92f)
