### ISSUE TITLE
automation of dnssec trust-anchor and auto-update

### ISSUE THREAD

**Issue by glenwiley** [getdnsapi/getdns#7]
On 2/11 we discussed where to apply unbound_anchor (Make install? what about local install options)
and how not to send out just a hard-coded root trust anchor.

Decision for 2/25 - Willem removes the hard-coded trust anchor. Make install will run unbound_anchor.

In later releases, we will enhance this.
(#104 from private repo)

**Comment by wtoorop** [comment]
The 1.2 release has Zero configuration DNSSEC, which is a feature to automatically obtain and update root trust-anchors, even when getdns is linked against an application in user space.
See also: https://getdnsapi.net/releases/getdns-1-2-0/
