### ISSUE TITLE
C and nodejs sample code for edns-client-subnet

### ISSUE THREAD

**Issue by gmadkat** [getdnsapi/getdns#72]

**Comment by saradickinson** [comment]
@wtoorop Can this issue be closed?

**Comment by wtoorop** [comment]
Op 19-04-17 om 14:26 schreef saradickinson:
> @wtoorop <https://github.com/wtoorop> Can this issue be closed?

@saradickinson I don't know. @amankin requested the example code.
@amankin do you still want this example?

**Comment by wtoorop** [comment]
Well at least we now have the edns_client_subnet_private setting, so closing...
