### ISSUE TITLE
Implement DNS cookies

### ISSUE THREAD

**Issue by shuque** [getdnsapi/getdns#90]
Implement support for DNS cookies, as being standardized in https://tools.ietf.org/html/draft-ietf-dnsop-cookies-00

Can be tested against servers running BIND 9.10 or later, which calls its implementation Source Identity Tokens (SIT), and which currently uses experimental EDNS0 option code 65001.

**Comment by wtoorop** [comment]
Implemented with commit 00f04781
Enable with --enable-draft-edns-cookies option and then use the edns_cookies extension.
