### ISSUE TITLE
set userarg with getdns_context_set_context_update_callback()

### ISSUE THREAD

**Issue by wtoorop** [getdnsapi/getdns#91]

**Comment by wtoorop** [comment]
We cannot just do because it breaks the user API.  We have to introduce a new function to do this correctly also in the spec.  After a while we might be able to remove the old function if all parties agree it is safe.

What about calling it getdns_context_set_update_callback instead of getdns_context_set_context_update_callback?  I.e.:

getdns_return_t getdns_context_set_update_callback(getdns_context *context, void *usearg, void (*value)(getdns_context *context, getdns_context_code_t changed_item, void *userarg));

**Comment by ngoyal** [comment]
Since this is an API change/enhancement, would it make sense to allow multiple update listeners to be attached to a context?  Basically each context could maintain a list of listeners that fire off when an update occurs rather than a limit of 1

**Comment by wtoorop** [comment]
Subscribing and unsubscribing to context changes makes sense, but I am
reluctant to add this state bookkeeping in the library.  Better to push
those sort of things to the client as much as possible.  If we put in a
getter for the current callback + user arg, the user can implement such
a scheme itself easily.  I.e.:

struct userarg_callback {
	void *userarg;
	void (*callback) (getdns_context *, getdns_context_code_t, void *);
}

void my_cb(getdns_context *context, getdns_context_code_t code, void
*userarg)
{
	struct userarg_callback *prev_cb = (struct userarg_callback *)userarg;

	if (prev_cb && prev_cb->callback)
		prev_cb->callback(context, code, prev_cb->userarg);

	/* Do your own things */
}

struct userarg_callback *prev_cb = malloc(sizeof(struct userarg_callback));

if ((r = getdns_context_get_update_callback(context, &prev_cb->userarg,
&prev_cb->callback)))
	return r;

if ((r = getdns_context_set_update_callback(context, prev_cb, my_cb)))
	return r;

What do you think?


Op 02-04-15 om 17:38 schreef ngoyal:

**Comment by ngoyal** [comment]
Yes I can see that as well.  I think if a getter is added then that makes sense.  I think the getter in general is a good idea since the user can also then do some cleanup steps on a user_arg before a context is destroyed, if needed.

**Comment by wtoorop** [comment]
Done with commit 87eb9307
