### ISSUE TITLE
Review ordering of entries in response dict

### ISSUE THREAD

**Issue by saradickinson** [getdnsapi/getdns#93]
At the demo at IETF92 it was commented that ordering the response dict alphabetically (as is currently done) may not be the most correct methodology. For example when both A and AAAA records are returned this means that IPv4 end points are listed before IPv6 end points whereas the IPv6 endpoints should be used first if available.

**Comment by wtoorop** [comment]
Actually the order in which the addresses appear in the just_address_answers section of the response dict is determined by which query is scheduled first.  Commit c9a61bd9 now has the order such that AAAA is scheduled first when using the getdns_address(_sync) function.   You call still use the other scheduling order by using getdns_general with rrtype A and the return_both_v4_and_v6 extension.
